#!/usr/bin/env bash

export GIT_PROJ_ROOT=`git rev-parse --show-toplevel`
${GIT_PROJ_ROOT}/project/victor/build-victor.sh \
		-c Release \
		-DANKI_DISABLE_ALEXA=1 \
		-DANKI_PRIVACY_GUARD=1 \
		-DOSKR_ENDPOINTS=1 \
		-DREMOTE_CONSOLE_ENABLED=1 \
		-DANKI_PROFILING_ENABLED=0 \
		-DANKI_REPORT_ERRORS_TO_DAS=0 \
		-DANKI_REPORT_ERRORS_WITH_STRVAL_TO_DAS=0 \
		-DANKI_MESSAGE_PROFILER_ENABLED=0 \
		-DANKI_BREADCRUMBS=0 \
		-DANKI_BUILD_OPENCL_ION_MEM_EXAMPLE=0 \
		-DUSE_ANKITRACE=OFF \
		-a -DAUDIO_RELEASE=ON \
		"$@"
