#!/bin/bash

DIAG="/data/diagnostics"
DIAG_TAR="$DIAG/logs.tar.bz2"
DIAG_LOGS="$DIAG/logs"

SYSLOGS=("/data/boot.log" "/factory/log0" "/factory/log1" "/run/update-engine/error")

delete_output () {
    rm -rf $DIAG_TAR
    rm -rf $DIAG_LOGS
}

collect_logs () {
    mkdir -p $DIAG_LOGS
    mkdir -p $DIAG_LOGS/networkmanager

    ps | grep anki > $DIAG_LOGS/ps
    logcat -dt2000 > $DIAG_LOGS/logcat
    logcat -dt 2000 vic-switchboard:V *:S > $DIAG_LOGS/logcat_sb
    ifconfig wlan0 > $DIAG_LOGS/ifconfig
    iwconfig wlan0 > $DIAG_LOGS/iwconfig
    netstat -ptlnu > $DIAG_LOGS/netstat-ptlnu
    dmesg > $DIAG_LOGS/dmesg
    top -n 1 > $DIAG_LOGS/top
    gateway=$(route | grep default | awk '{ print $2 }') && ping -c 4 "$gateway" > $DIAG_LOGS/ping-gateway
    ping -c 4 anki.com > $DIAG_LOGS/ping-anki
    cp -r /etc/NetworkManager/system-connections $DIAG_LOGS/networkmanager
}

compress () {
    TARFILES=()
    for f in ${SYSLOGS[*]}
    do
        if [ -f "$f" ]
        then
           TARFILES+=("$f")
        fi
    done

    tar -cvjf $DIAG_TAR $DIAG_LOGS ${TARFILES[*]}
}

delete_output
collect_logs
compress
