
useAndrewsPaths = false;

if useAndrewsPaths
    rootDir = fileparts(fileparts(fileparts(fileparts(which('makeMex.m')))));
    mexWrapperDir = fullfile(rootDir, 'coretech-common', 'matlab', 'mex');

    %%
    mex mexRegionProps.cpp
    %%
    mex mexClosestIndex.cpp
    %% 
    mex mexHist.cpp
    %%
    mex('mexGaussianBlur.cpp', ...
        fullfile(mexWrapperDir, 'mexWrappers.cpp'), ...
        '-I/usr/local/include/', ...
        ['-I' mexWrapperDir], ...
        '-L/usr/local/bin/', '-l opencv_core', '-l opencv_imgproc');
    %%
    mex('-g', 'mexBundleAdjust.cpp', ...
        fullfile(mexWrapperDir, 'mexWrappers.cpp'), ...
        '-I/usr/local/include/', ['-I' mexWrapperDir], ...
        '-L/usr/local/bin/', '-l opencv_core', '-l opencv_contrib', ...
        '-l opencv_calib3d');
else
%    compileVerbose = '-compatibleArrayDims '; 
   compileVerbose = '-v';

    rootDir = fileparts(fileparts(fileparts(fileparts(which('makeMex.m')))));
    rootDir(rootDir == '\') = '/';
    mexWrapperDir = fullfile(rootDir, 'coretech-common', 'matlab', 'mex');
    mexWrapperDir(mexWrapperDir == '\') = '/';

    if ismac()
        openCvLibDir = [rootDir, '/coretech-external/build/xcode4/opencv-2.4.6.1/lib/Debug/'];
        openCvVersionString = '';
    elseif ispc()
        openCvLibDir = [rootDir, '/coretech-external/build/msvc2010/opencv-2.4.6.1/lib/Release/'];
        openCvVersionString = '246';
    end

    openCvModules = {'calib3d', 'contrib', 'core', 'features2d', 'flann', 'highgui', 'imgproc', 'legacy', 'ml', 'nonfree', 'objdetect', 'ocl', 'photo', 'stitching', 'superres', 'video', 'videostab'};
    openCvIncludeDirs = cell(length(openCvModules)+1,1);
    openCvIncludeDirs{1} = [rootDir, '/coretech-external/opencv-2.4.6.1/include/'];
    for i = 1:length(openCvModules)
        openCvIncludeDirs{i+1} = [rootDir, '/coretech-external/opencv-2.4.6.1/modules/', openCvModules{i}, '/include'];
    end

    %%
    mex(compileVerbose, 'mexRegionProps.cpp');
    %%
    mex(compileVerbose, 'mexClosestIndex.cpp');
    %% 
    mex(compileVerbose, 'mexHist.cpp');
    %
    mex(compileVerbose, 'mexGaussianBlur.cpp', ...
        fullfile(mexWrapperDir, 'mexWrappers.cpp'), ...
        ['-I' openCvIncludeDirs{1}], ...
        ['-I' openCvIncludeDirs{2}], ...
        ['-I' openCvIncludeDirs{3}], ...
        ['-I' openCvIncludeDirs{4}], ...
        ['-I' openCvIncludeDirs{5}], ...
        ['-I' openCvIncludeDirs{6}], ...
        ['-I' openCvIncludeDirs{7}], ...
        ['-I' openCvIncludeDirs{8}], ...
        ['-I' openCvIncludeDirs{9}], ...
        ['-I' openCvIncludeDirs{10}], ...
        ['-I' openCvIncludeDirs{11}], ...
        ['-I' openCvIncludeDirs{12}], ...
        ['-I' openCvIncludeDirs{13}], ...
        ['-I' openCvIncludeDirs{14}], ...
        ['-I' openCvIncludeDirs{15}], ...
        ['-I' openCvIncludeDirs{16}], ...
        ['-I' openCvIncludeDirs{17}], ...
        ['-I' openCvIncludeDirs{18}], ...
        ['-I' mexWrapperDir], ...
        ['-L', openCvLibDir], ['-lopencv_core', openCvVersionString], ['-lopencv_imgproc', openCvVersionString]);
    %%
    mex(compileVerbose, '-g', 'mexBundleAdjust.cpp', ...
        fullfile(mexWrapperDir, 'mexWrappers.cpp'), ...
        ['-I' mexWrapperDir], ...
        ['-I' openCvIncludeDirs{1}], ...
        ['-I' openCvIncludeDirs{2}], ...
        ['-I' openCvIncludeDirs{3}], ...
        ['-I' openCvIncludeDirs{4}], ...
        ['-I' openCvIncludeDirs{5}], ...
        ['-I' openCvIncludeDirs{6}], ...
        ['-I' openCvIncludeDirs{7}], ...
        ['-I' openCvIncludeDirs{8}], ...
        ['-I' openCvIncludeDirs{9}], ...
        ['-I' openCvIncludeDirs{10}], ...
        ['-I' openCvIncludeDirs{11}], ...
        ['-I' openCvIncludeDirs{12}], ...
        ['-I' openCvIncludeDirs{13}], ...
        ['-I' openCvIncludeDirs{14}], ...
        ['-I' openCvIncludeDirs{15}], ...
        ['-I' openCvIncludeDirs{16}], ...
        ['-I' openCvIncludeDirs{17}], ...
        ['-I' openCvIncludeDirs{18}], ...
        ['-L', openCvLibDir], ['-lopencv_core', openCvVersionString], ['-lopencv_contrib', openCvVersionString], ['-lopencv_calib3d', openCvVersionString]); 
    %%
    mex(compileVerbose, '-g', 'mex_cp2tform_projective.cpp', ...
        fullfile(mexWrapperDir, 'mexWrappers.cpp'), ...
        ['-I' mexWrapperDir], ...
        ['-I' openCvIncludeDirs{1}], ...
        ['-I' openCvIncludeDirs{2}], ...
        ['-I' openCvIncludeDirs{3}], ...
        ['-I' openCvIncludeDirs{4}], ...
        ['-I' openCvIncludeDirs{5}], ...
        ['-I' openCvIncludeDirs{6}], ...
        ['-I' openCvIncludeDirs{7}], ...
        ['-I' openCvIncludeDirs{8}], ...
        ['-I' openCvIncludeDirs{9}], ...
        ['-I' openCvIncludeDirs{10}], ...
        ['-I' openCvIncludeDirs{11}], ...
        ['-I' openCvIncludeDirs{12}], ...
        ['-I' openCvIncludeDirs{13}], ...
        ['-I' openCvIncludeDirs{14}], ...
        ['-I' openCvIncludeDirs{15}], ...
        ['-I' openCvIncludeDirs{16}], ...
        ['-I' openCvIncludeDirs{17}], ...
        ['-I' openCvIncludeDirs{18}], ...
        ['-L', openCvLibDir], ['-lopencv_core', openCvVersionString], ['-lopencv_contrib', openCvVersionString], ['-lopencv_calib3d', openCvVersionString]); 
end
