import re

# prebuilt_jar rule for everything in libs dir
jar_deps = []
for jarfile in glob(['libs/*.jar']):
  name = 'lib_' + re.sub(r'^.*/([^/]+)\.jar$', r'\1', jarfile)
  jar_deps.append(':' + name)
  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

android_library(
  name = 'hockey-app',
  srcs = glob(['src/**/*.java']),
  manifest = 'src/main/AndroidManifest.xml',
  source = '1.6',
  target = '1.6',
  deps = jar_deps,
  visibility = ['PUBLIC'],
)
