mex mexCameraCapture.cpp ...
    ../../../coretech-common/matlab/mex/mexWrappers.cpp ...
    -I../../../coretech-external/opencv-2.4.6.1/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/core/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/highgui/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/imgproc/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/flann/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/photo/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/video/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/features2d/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/objdetect/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/calib3d/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/ml/include/ ...
    -I../../../coretech-external/opencv-2.4.6.1/modules/contrib/include/ ...
    -I../../../coretech-common/matlab/mex/ ...
    -I../../../coretech-common/include/ ...
    -L../../../coretech-external/build/xcode4/opencv-2.4.6.1/lib/Release/ ...
    -l opencv_core -l opencv_highgui -l opencv_imgproc

% %%
% mex mexCameraCapture.cpp /Users/andrew/Code/mex/mexWrappers.cpp ...
%     -I/usr/local/include/ -I/Users/andrew/Code/mex/ ...
%     -L/usr/local/bin/ -l opencv_core -l opencv_highgui -l opencv_imgproc
