mex mexCameraCapture.cpp /Users/andrew/Code/mex/mexWrappers.cpp ...
    -I/usr/local/include/ -I/Users/andrew/Code/mex/ ...
    -L/usr/local/bin/ -l opencv_core -l opencv_highgui -l opencv_imgproc
%-L/usr/lib -l stdc++