/**
File: utilities_c.c
Author: Peter Barnum
Created: 2013

Copyright Anki, Inc. 2013
For internal use only. No part of this code may be used without a signed non-disclosure agreement with Anki, inc.
**/

#include "coretech/common/robot/utilities_c.h"

//////////////////////////////////////////////////////////////////////////////
// COMPARISON MACROS
//////////////////////////////////////////////////////////////////////////////

// Tolerance for which two floating point numbers are considered equal (to deal
// with imprecision in floating point representation).
#define FLOATING_POINT_COMPARISON_TOLERANCE 1e-5f

// TRUE if x is near y by the amount epsilon, else FALSE
#ifndef FLT_NEAR
#define FLT_NEAR(x,y) ( ((x)==(y)) || (((x) > (y)-(FLOATING_POINT_COMPARISON_TOLERANCE))      && ((x) < (y)+(FLOATING_POINT_COMPARISON_TOLERANCE))) )
#endif
//////////////////////////////////////////////////////////////////////////////



// This table was generated by the function InitializeCRC32Table()
#define CRC32_TABLE_LENGTH 256
static const u32 crc32Table[CRC32_TABLE_LENGTH] = {0x0, 0x77073096, 0xEE0E612C, 0x990951BA, 0x76DC419, 0x706AF48F, 0xE963A535, 0x9E6495A3, 0xEDB8832, 0x79DCB8A4, 0xE0D5E91E, 0x97D2D988, 0x9B64C2B, 0x7EB17CBD, 0xE7B82D07, 0x90BF1D91, 0x1DB71064, 0x6AB020F2, 0xF3B97148, 0x84BE41DE, 0x1ADAD47D, 0x6DDDE4EB, 0xF4D4B551, 0x83D385C7, 0x136C9856, 0x646BA8C0, 0xFD62F97A, 0x8A65C9EC, 0x14015C4F, 0x63066CD9, 0xFA0F3D63, 0x8D080DF5, 0x3B6E20C8, 0x4C69105E, 0xD56041E4, 0xA2677172, 0x3C03E4D1, 0x4B04D447, 0xD20D85FD, 0xA50AB56B, 0x35B5A8FA, 0x42B2986C, 0xDBBBC9D6, 0xACBCF940, 0x32D86CE3, 0x45DF5C75, 0xDCD60DCF, 0xABD13D59, 0x26D930AC, 0x51DE003A, 0xC8D75180, 0xBFD06116, 0x21B4F4B5, 0x56B3C423, 0xCFBA9599, 0xB8BDA50F, 0x2802B89E, 0x5F058808, 0xC60CD9B2, 0xB10BE924, 0x2F6F7C87, 0x58684C11, 0xC1611DAB, 0xB6662D3D, 0x76DC4190, 0x1DB7106, 0x98D220BC, 0xEFD5102A, 0x71B18589, 0x6B6B51F, 0x9FBFE4A5, 0xE8B8D433, 0x7807C9A2, 0xF00F934, 0x9609A88E, 0xE10E9818, 0x7F6A0DBB, 0x86D3D2D, 0x91646C97, 0xE6635C01, 0x6B6B51F4, 0x1C6C6162, 0x856530D8, 0xF262004E, 0x6C0695ED, 0x1B01A57B, 0x8208F4C1, 0xF50FC457, 0x65B0D9C6, 0x12B7E950, 0x8BBEB8EA, 0xFCB9887C, 0x62DD1DDF, 0x15DA2D49, 0x8CD37CF3, 0xFBD44C65, 0x4DB26158, 0x3AB551CE, 0xA3BC0074, 0xD4BB30E2, 0x4ADFA541, 0x3DD895D7, 0xA4D1C46D, 0xD3D6F4FB, 0x4369E96A, 0x346ED9FC, 0xAD678846, 0xDA60B8D0, 0x44042D73, 0x33031DE5, 0xAA0A4C5F, 0xDD0D7CC9, 0x5005713C, 0x270241AA, 0xBE0B1010, 0xC90C2086, 0x5768B525, 0x206F85B3, 0xB966D409, 0xCE61E49F, 0x5EDEF90E, 0x29D9C998, 0xB0D09822, 0xC7D7A8B4, 0x59B33D17, 0x2EB40D81, 0xB7BD5C3B, 0xC0BA6CAD, 0xEDB88320, 0x9ABFB3B6, 0x3B6E20C, 0x74B1D29A, 0xEAD54739, 0x9DD277AF, 0x4DB2615, 0x73DC1683, 0xE3630B12, 0x94643B84, 0xD6D6A3E, 0x7A6A5AA8, 0xE40ECF0B, 0x9309FF9D, 0xA00AE27, 0x7D079EB1, 0xF00F9344, 0x8708A3D2, 0x1E01F268, 0x6906C2FE, 0xF762575D, 0x806567CB, 0x196C3671, 0x6E6B06E7, 0xFED41B76, 0x89D32BE0, 0x10DA7A5A, 0x67DD4ACC, 0xF9B9DF6F, 0x8EBEEFF9, 0x17B7BE43, 0x60B08ED5, 0xD6D6A3E8, 0xA1D1937E, 0x38D8C2C4, 0x4FDFF252, 0xD1BB67F1, 0xA6BC5767, 0x3FB506DD, 0x48B2364B, 0xD80D2BDA, 0xAF0A1B4C, 0x36034AF6, 0x41047A60, 0xDF60EFC3, 0xA867DF55, 0x316E8EEF, 0x4669BE79, 0xCB61B38C, 0xBC66831A, 0x256FD2A0, 0x5268E236, 0xCC0C7795, 0xBB0B4703, 0x220216B9, 0x5505262F, 0xC5BA3BBE, 0xB2BD0B28, 0x2BB45A92, 0x5CB36A04, 0xC2D7FFA7, 0xB5D0CF31, 0x2CD99E8B, 0x5BDEAE1D, 0x9B64C2B0, 0xEC63F226, 0x756AA39C, 0x26D930A, 0x9C0906A9, 0xEB0E363F, 0x72076785, 0x5005713, 0x95BF4A82, 0xE2B87A14, 0x7BB12BAE, 0xCB61B38, 0x92D28E9B, 0xE5D5BE0D, 0x7CDCEFB7, 0xBDBDF21, 0x86D3D2D4, 0xF1D4E242, 0x68DDB3F8, 0x1FDA836E, 0x81BE16CD, 0xF6B9265B, 0x6FB077E1, 0x18B74777, 0x88085AE6, 0xFF0F6A70, 0x66063BCA, 0x11010B5C, 0x8F659EFF, 0xF862AE69, 0x616BFFD3, 0x166CCF45, 0xA00AE278, 0xD70DD2EE, 0x4E048354, 0x3903B3C2, 0xA7672661, 0xD06016F7, 0x4969474D, 0x3E6E77DB, 0xAED16A4A, 0xD9D65ADC, 0x40DF0B66, 0x37D83BF0, 0xA9BCAE53, 0xDEBB9EC5, 0x47B2CF7F, 0x30B5FFE9, 0xBDBDF21C, 0xCABAC28A, 0x53B39330, 0x24B4A3A6, 0xBAD03605, 0xCDD70693, 0x54DE5729, 0x23D967BF, 0xB3667A2E, 0xC4614AB8, 0x5D681B02, 0x2A6F2B94, 0xB40BBE37, 0xC30C8EA1, 0x5A05DF1B, 0x2D02EF8D};

#define MAX_PRINTF_DIGITS 50
#define PRINTF_BUFFER_SIZE 1024
int printfBuffer[PRINTF_BUFFER_SIZE];

#if 1
void explicitPrintf(int (*writeChar)(int), int reverseEachFourCharacters, const char *format, ...)
{
  const char * const formatStart = format;
  int numCharacters;
  int i;
  va_list arguments;

  // If null, default to putchar
  if (writeChar == 0) {
    writeChar = putchar;
  }

  // Count the number of characters
  numCharacters = 0;
  while(*format != 0x00)
  {
    numCharacters++;
    format++;
  }
  format = formatStart;

  if(reverseEachFourCharacters)
    numCharacters += 3;

  numCharacters = MIN(numCharacters, PRINTF_BUFFER_SIZE-5);

  // Reverse the string
  if(reverseEachFourCharacters) {
    for(i=0; i<numCharacters; i+=4) {
      printfBuffer[i] = format[i+3];
      if(format[i+3] == 0x00) {
        printfBuffer[i+1] = 0x00;
      } else {
        printfBuffer[i+1] = format[i+2];
        if(format[i+2] == 0x00) {
          printfBuffer[i+2] = 0x00;
        } else {
          printfBuffer[i+2] = format[i+1];
          if(format[i+1] == 0x00) {
            printfBuffer[i+3] = 0x00;
          } else {
            printfBuffer[i+3] = format[i];
          }
        }
      }
    }
  } else {
    for(i=0; i<numCharacters; i++) {
      printfBuffer[i] = format[i];
    }
  }

  va_start(arguments, format);

  for(i=0; i<numCharacters; i++) {
    if(printfBuffer[i] == '%') {
      const char percentChar = printfBuffer[i+1];
      i++;

      if(percentChar == 'd') {
        const s32 value = va_arg(arguments, s32);
        PrintS32(writeChar, value);
        format++;
      } else if(percentChar == 'x') {
        const u32 value = va_arg(arguments, u32);
        PrintU32Hex(writeChar, value);
        format++;
      } else if(percentChar == 'f') {
        // TODO: should this be double?
        const f64 value = va_arg(arguments, f64);
        PrintF64(writeChar, value);
        format++;
      } else if(percentChar == 'e') {
        // TODO: should this be double?
        const f64 value = va_arg(arguments, f64);
        PrintF64WithExponent(writeChar, value);
        format++;
      } else if(percentChar == 's') {
        const char * stringArgument = va_arg(arguments, char*);
        while(*stringArgument != 0x00) {
          writeChar(*stringArgument);
          stringArgument++;
        }
      }
      else {
        if(printfBuffer[i] == 0x00)
          break;

        writeChar('%');
        writeChar(printfBuffer[i]);
      }
    } else {
      if(printfBuffer[i] == 0x00)
        break;

      writeChar(printfBuffer[i]);
    }
  } // for(i=0; i<numCharacters; i++)

  va_end(arguments);
}

#endif

void PrintF64(int (*writeChar)(int), f64 value)
{
  const s32 maxDecimalDigits = 6;
  f64 decimalPart;

  s32 numDecimalDigitsUsed = 0;

  // If null, default to putchar
  if (writeChar == 0) {
    writeChar = putchar;
  }

  if(value < 0.0) {
    writeChar('-');
    value = -value;
  }

  decimalPart = value - (f64)floorf(value);

  // Print the part before the decimal digit

  if(value > 10000000000.0) {
    const f64 topPart = (f64)value / 10000000000.0;
    PrintS32(writeChar, (s32)floorf(topPart));
    writeChar('.');
    writeChar('.');
    writeChar('.');
    return;
  }

  // If value is close enough to the ceil value, just print the ceil value.
  if (FLT_NEAR(value, (f64)ceilf(value))) {
    PrintS32(writeChar, (s32)ceilf(value));
    writeChar('.');
    writeChar('0');
    return;
  }

  PrintS32(writeChar, (s32)floorf(value));

  // The remainder of this function prints the part after the decimal digit
  value = decimalPart;

  writeChar('.');

  if(value < (1.0f / powf(10.0f, maxDecimalDigits-1))) {
    writeChar('0');

    return;
  }

  // This loop prints out the part after the decimal point
  while(value > 0.0f && numDecimalDigitsUsed < maxDecimalDigits) {
    s32 curDigit;

    numDecimalDigitsUsed++;

    value *= 10.0f;

    if(value < (1.0f - FLOATING_POINT_COMPARISON_TOLERANCE)) {
      writeChar('0');
      continue;
    }

    if (FLT_NEAR(value, ceilf(value))) {
      curDigit = (s32) round(value);
      numDecimalDigitsUsed = maxDecimalDigits; // To exit while loop since this is the last digit we want to print
    } else {
      curDigit = (s32)(floorf((f32)(value)));
    }

    // This if statement should nenver be true, but it sometimes is on the myriad1. This will output "BUG".
    //if(value < 0.0f){
    //  writeChar('B');
    //  writeChar('U');
    //  writeChar('G');
    //  writeChar('4');
    //  return;
    //}

    //if(ABS(value) < 0.00000000001f){
    //  writeChar('B');
    //  writeChar('U');
    //  writeChar('G');
    //  writeChar('5');
    //  return;
    //}

    //if(curDigit < 0){
    //  writeChar('B');
    //  writeChar('U');
    //  writeChar('G');
    //  writeChar('6');
    //  return;
    //}

    writeChar(curDigit + 48);

    value = value - (f32)curDigit;
  }

  return;
} // void printFloat(f32 value)

void PrintF64WithExponent(int (*writeChar)(int), f64 value)
{
  double significand;
  int exponent;

  // If null, default to putchar
  if (writeChar == 0) {
    writeChar = putchar;
  }

  significand = frexpf(value, &exponent);

  PrintF64(writeChar, significand);
  writeChar('*');
  writeChar('2');
  writeChar('^');

  PrintS32(writeChar, exponent);

  return;
} // void printFloat(f32 value)

s32 SnprintfCommasS32(char *buffer, const s32 bufferLength, const s32 value)
{
  s32 numberLength;
  s32 numCommas;
  s32 numWritten;
  s32 iOut;

  char tmpBuffer[128];

  snprintf(tmpBuffer, 128, "%d", value);

  numberLength = (s32)(strlen(tmpBuffer));

  if(value < 0)
    numCommas = (numberLength-2) / 3;
  else
    numCommas = (numberLength-1) / 3;

  if((numberLength + numCommas + 1) > bufferLength)
    return 0;

  numWritten = 0;
  iOut = numberLength + numCommas - 1;
  while(iOut >= 0) {
    if(numWritten > 0 && (numWritten%3 == 0) && (tmpBuffer[numberLength - numWritten - 1] != '-')) {
      buffer[iOut] = ',';
      iOut--;
    }

    buffer[iOut] = tmpBuffer[numberLength - numWritten - 1];
    iOut--;
    numWritten++;
  }

  buffer[numberLength + numCommas] = '\0';

  return numberLength + numCommas;
}

void PrintS32(int (*writeChar)(int), s32 value)
{
  int digits[MAX_PRINTF_DIGITS];

  s32 digitIndex = -1;

  for(digitIndex=0; digitIndex<MAX_PRINTF_DIGITS; digitIndex++) {
    digits[digitIndex] = 0;
  }

  // If null, default to putchar
  if (writeChar == 0) {
    writeChar = putchar;
  }

  if(value < 0) {
    writeChar('-');
    value = -value;
  }

  if(value == 0) {
    writeChar('0');
    return;
  }

  digitIndex=0;
  while(value > 0) {
    const s32 curDigit = (value - (10*(value/10)));
    //const int curDigit = ABS(value) % 10;

    // This if statement should never be true, but it sometimes is on the myriad1. This will output "BUG".
    //if(value < 0){
    //  // BUG1
    //  digits[digitIndex++] = 1;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    //if(value == 0){
    //  // BUG2
    //  digits[digitIndex++] = 2;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    //if(curDigit < 0){
    //  // BUG3
    //  digits[digitIndex++] = 3;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    digits[digitIndex++] = curDigit;

    value /= 10;
  }

  digitIndex--;
  for( ; digitIndex>=0; digitIndex--) {
    writeChar(digits[digitIndex] + 48);
  }

  return;
} // void printInt(s32 value)

void PrintU32Hex(int (*writeChar)(int), u32 value)
{
  int digits[MAX_PRINTF_DIGITS];

  s32 digitIndex = -1;

  for(digitIndex=0; digitIndex<MAX_PRINTF_DIGITS; digitIndex++) {
    digits[digitIndex] = 0;
  }

  // If null, default to putchar
  if (writeChar == 0) {
    writeChar = putchar;
  }

  if(value == 0) {
    writeChar('0');
    return;
  }

  digitIndex=0;
  while(value > 0) {
    const s32 curDigit = (value - (16*(value/16)));
    //const int curDigit = ABS(value) % 10;

    // This if statement should never be true, but it sometimes is on the myriad1. This will output "BUG".
    //if(value < 0){
    //  // BUG1
    //  digits[digitIndex++] = 1;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    //if(value == 0){
    //  // BUG2
    //  digits[digitIndex++] = 2;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    //if(curDigit < 0){
    //  // BUG3
    //  digits[digitIndex++] = 3;
    //  digits[digitIndex++] = 23;
    //  digits[digitIndex++] = 37;
    //  digits[digitIndex++] = 18;
    //  break;
    //}

    digits[digitIndex++] = curDigit;

    value /= 16;
  }

  digitIndex--;
  for( ; digitIndex>=0; digitIndex--) {
    const s32 curDigit = digits[digitIndex];
    if(curDigit < 10) {
      writeChar(curDigit + 48);
    } else {
      writeChar(curDigit + 55);
    }
  }

  return;
} // void printInt(s32 value)

s32 IsPowerOfTwo(u32 x)
{
  // While x is even and greater than 1, keep dividing by two
  while (((x & 1) == 0) && x > 1)
    x >>= 1;

  return (x == 1);
}

s32 IsOdd(const s32 x)
{
  if(((x>>1)<<1) == x)
    return 0;
  else
    return 1;
}

u32 Log2u32(u32 x)
{
  u32 powerCount = 0;
  // While x is even and greater than 1, keep dividing by two
  while (x >>= 1) {
    powerCount++;
  }

  return powerCount;
}

u64 Log2u64(u64 x)
{
  u64 powerCount = 0;
  // While x is even and greater than 1, keep dividing by two
  while (x >>= 1) {
    powerCount++;
  }

  return powerCount;
}

// Based off Hacker's delight, 2nd edition
#ifdef REINITIALZE_CRC32_TABLE
void InitializeCRC32Table()
{
  s32 j;
  u32 byte, crc, mask;
  for (byte = 0; byte <= 255; byte++) {
    crc = byte;
    for (j = 7; j >= 0; j--) {    // Do eight times.
      mask = -(crc & 1);
      crc = (crc >> 1) ^ (0xEDB88320 & mask);
    }
    crc32Table[byte] = crc;
    CoreTechPrint("0x%x, ", crc);
  }
}
#endif // #ifdef REINITIALZE_CRC32_TABLE

// Based off Hacker's delight, 2nd edition
u32 ComputeCRC32(const void * data, const s32 dataLength, const u32 initialCRC)
{
  s32 i = 0;
  u32 crc = initialCRC;

  for(i=0; i<dataLength; i++) {
    const s32 index = i;
    const u32 byte = ((u8*)data)[index];
    //CoreTechPrint("%d\n", byte);
    crc = (crc >> 8) ^ crc32Table[(crc ^ byte) & 0xFF];
    //CoreTechPrint("%d (%d) = 0x%x\n", i, byte, crc);
  }

  // Technically, this should return ~crc, but that would make it wierd to chain multiple calls of this function
  return crc;
}
