#include "BlockDefinitionMacros.h"

//START_BLOCK_DEFINITION(FUEL, (44.f,44.f,44.f), (0xff,0x0,0x0))
//ADD_ALL_FACES(26.f, Vision::MARKER_BATTERIES)
//END_BLOCK_DEFINITION

// Update to 23mm for Victor cubes once we have DVT2 cubes (VIC-945)
#define DEFAULT_BLOCK_MARKER_SIZE 23.f

/*
// Only 3 blocks for CREEP test
START_BLOCK_DEFINITION(KITTY, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_KITTY)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(BEE, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BEE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SPIDER, (44.f,44.f,44.f), RED)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SPIDER)
END_BLOCK_DEFINITION

// NOTE: Bullseye blocks have 23mm markers!
START_BLOCK_DEFINITION(BULLSEYE2, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(23.f, Vision::MARKER_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(BULLSEYE2_INVERTED, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(23.f, Vision::MARKER_INVERTED_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FIRE, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_FIRE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SQTARGET, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SQUAREPLUSCORNERS)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ANGRYFACE, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANGRYFACE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(STAR5, (44.f,44.f,44.f), DARKGREEN)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_STAR5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(DICE, (16.f,16.f,16.f), OFFWHITE)
ADD_FACE_CODE(FRONT_FACE,  12.f, Vision::MARKER_DICE1, PreActionOrientation::NONE)
ADD_FACE_CODE(BACK_FACE,   12.f, Vision::MARKER_DICE2, PreActionOrientation::NONE)
ADD_FACE_CODE(LEFT_FACE,   12.f, Vision::MARKER_DICE3, PreActionOrientation::NONE)
ADD_FACE_CODE(RIGHT_FACE,  12.f, Vision::MARKER_DICE4, PreActionOrientation::NONE)
ADD_FACE_CODE(TOP_FACE,    12.f, Vision::MARKER_DICE5, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, 12.f, Vision::MARKER_DICE6, PreActionOrientation::NONE)
END_BLOCK_DEFINITION

// NOTE: Flag blocks have 23mm markers!
START_BLOCK_DEFINITION(FLAG, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_CHECKEREDFLAG)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FLAG2, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_CHECKEREDFLAG2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FLAG_INVERTED, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_INVERTED_CHECKEREDFLAG)
END_BLOCK_DEFINITION

// Remove this one if it is also used on the mat!
START_BLOCK_DEFINITION(ANKILOGO, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANKILOGO)
END_BLOCK_DEFINITION

// Number blocks
START_BLOCK_DEFINITION(NUMBER1, (44.f,44.f,44.f), DARKGRAY)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_1)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER2, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER3, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_3)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER4, (44.f,44.f,44.f), ORANGE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_4)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER5, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER6, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_6)
END_BLOCK_DEFINITION
*/

#ifdef SIMULATOR
// These are the "real" Victor cube definitions, currently only available in simulation

// TODO: Swap these in to replace the Cozmo blocks above once we have DVT2 cubes (VIC-945)
// Victor Active Block #1 (w/ circle markers)
START_BLOCK_DEFINITION(LIGHTCUBE1, (44.f,44.f,44.f), ORANGE)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Victor Active Block #2 (w/ square markers) [Not in production, but used in Webots tests]
START_BLOCK_DEFINITION(LIGHTCUBE2, (44.f,44.f,44.f), YELLOW)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_SQUARE_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Victor Active Block #3, Same as Cozmo LightCube3, but with light-on-dark markers [Not in production, but used in Webots tests]
START_BLOCK_DEFINITION(LIGHTCUBE3, (44.f,44.f,44.f), RED)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LIGHTONDARK_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

#else
// Remove (or comment out) Cozmo block definitions once we have real DVT3 cubes (VIC-945)

// Cozmo Active Block #1 (w/ 6 different sides)
START_BLOCK_DEFINITION(LIGHTCUBE1, (44.f,44.f,44.f), ORANGE)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_FRONT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_BACK,PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_LEFT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_RIGHT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_TOP, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Cozmo Active Block #2
START_BLOCK_DEFINITION(LIGHTCUBE2, (44.f,44.f,44.f), YELLOW)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_FRONT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_BACK,PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_LEFT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_RIGHT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_TOP, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Victor Active Block #3, Same as Cozmo LightCube3, but with light-on-dark markers [Not in production, but used in Webots tests]
START_BLOCK_DEFINITION(LIGHTCUBE3, (44.f,44.f,44.f), RED)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

#endif

// "Ghost" Active Block - NOT FOR USE IN BLOCKWORLD (these are hacks for behaviors)
START_BLOCK_DEFINITION(LIGHTCUBE_GHOST, (44.f,44.f,44.f), WHITE) // White like ghosts
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_UNKNOWN)
END_BLOCK_DEFINITION

/*
//Exclamation point
START_BLOCK_DEFINITION(BANGBANGBANG, (44.f,44.f,44.f), RED)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG)
END_BLOCK_DEFINITION
*/

/*
// Exclamation mark - 2x1
START_BLOCK_DEFINITION(BANGBANGBANG, (88.f,44.f,44.f), GREEN)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ARROW, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ARROW)
END_BLOCK_DEFINITION
*/

#undef DEFAULT_BLOCK_MARKER_SIZE
