#!/bin/sh

####
## THIS ROBOT IS HACKED for FCC TEST
###

# Enable power rails required for GPIO, LCD, IMU and Camera but not yet controlled by device tree
# TODO Configure device tree to properly control these regulators.
echo 1 > /sys/kernel/debug/regulator/8916_l8/enable
echo 1 > /sys/kernel/debug/regulator/8916_l17/enable
echo 1 > /sys/kernel/debug/regulator/8916_l4/enable

# @nathan-anki  - to stop overheating, limit CPU to 533MHz, RAM to 400MHz
echo 533333 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo disabled > /sys/kernel/debug/msm_otg/bus_voting  # This prevents USB from pinning RAM to 400MHz
echo 0 > /sys/kernel/debug/msm-bus-dbg/shell-client/update_request
echo 1 > /sys/kernel/debug/msm-bus-dbg/shell-client/mas
echo 512 > /sys/kernel/debug/msm-bus-dbg/shell-client/slv
echo 0 > /sys/kernel/debug/msm-bus-dbg/shell-client/ab
echo active clk2 0 1 max 400000 > /sys/kernel/debug/rpm_send_msg/message # Max RAM freq in KHz = 400MHz
echo 1 > /sys/kernel/debug/msm-bus-dbg/shell-client/update_request
#End clock speed limits

# TODO Move this power rail controll into the camera driver
CAM_REG_GPIO=83
if [ ! -d /sys/class/gpio/gpio$CAM_REG_GPIO ]; then
    echo $CAM_REG_GPIO > /sys/class/gpio/export
fi
echo out > /sys/class/gpio/gpio$CAM_REG_GPIO/direction
echo 1 > /sys/class/gpio/gpio$CAM_REG_GPIO/value
# End camera force hack

# Print the ID on the face
# emr-cat prints a placeholder value even on error
SERIALNO=`/bin/emr-cat e`
HAVE_EMR=$?

# And put the serial number in properties
for i in `seq 1 5`;
do
    setprop ro.serialno $SERIALNO
    if test ! -z `getprop ro.serialno`; then break; fi
    sleep 1;
done

if [ -x /usr/bin/vic-christen ]; then
    /usr/bin/vic-christen
fi

if $HAVE_EMR; then
  echo $SERIALNO > /sys/class/android_usb/android0/iSerial
  echo 2 1 w $SERIALNO | /system/bin/display
fi
echo 2 2 w `getprop persist.anki.robot.name` | /system/bin/display

/bin/hostname `getprop persist.anki.robot.name | tr ' ' '-'`

## Enter FCC test mode - WiFi will NOT work on this robot
rmmod wlan.ko
insmod /usr/lib/modules/3.18.66/extra/wlan.ko con_mode=5
iwpriv wlan0 ftm 1
iwpriv wlan0 ena_chain 2

## Fire up the FCC menu test
/anki/menuman.sh &

exit 0
