#!/bin/sh
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# Check for tabs in any new lines in any C/C++ files to be committed. The last grep
# command contains a literal tab character because (ba)sh turns \t into t, not a tab.
# Adapted from https://stackoverflow.com/questions/3985463/prevent-pushes-to-git-containing-tabs-in-certain-files-e-g-cpp-h-cmakeli
if git diff --name-only $against | egrep -i '(\.(c|cpp|h|hpp)$)' | xargs git diff -U0 $against | grep -n '^+.*	' ; then
  echo "Tabs are not allowed in C/C++ per the Anki coding standard (https://github.com/anki/dev-docs/blob/master/docs/coding-standards/cpp.md).\nPlease correct the above instances."
  exit 1
fi

