#ifndef __HARDWARE_H
#define __HARDWARE_H


static const uint32_t recovery_value = 0xCAFEBABE;
static volatile uint32_t * const recovery_word = (uint32_t*) 0x20001FFC;
static const int32_t* const HW_VERSION = (const int32_t*) 0x00000040;

// THESE SHOULD BE DONE IN THE PROJECT DEFINE LIST
//#define GENERATE_WHITE_NOISE

const uint8_t CAMERA_ADDR = 0x31;
const uint8_t CAMERA_EXPOSURE = 0x3;
const uint8_t CAMERA_GAIN = 0x70;

#define EP1_HEADBOARD

// All of these are for EP1 and EP2
GPIO_PIN_SOURCE(I2C_SCL, PTE, 24);
GPIO_PIN_SOURCE(I2C_SDA, PTB, 1);

GPIO_PIN_SOURCE(BODY_UART_RX, PTD, 6);
GPIO_PIN_SOURCE(BODY_UART_TX, PTD, 7);

#define CAMERA_DATA_GPIO GPIOC_PDIR
GPIO_PIN_SOURCE(AUDIO_STANDBY, PTE, 25);

GPIO_PIN_SOURCE(WS, PTD, 4);

GPIO_PIN_SOURCE(CAM_D1, PTC, 1);
GPIO_PIN_SOURCE(CAM_D2, PTC, 2);
GPIO_PIN_SOURCE(CAM_D3, PTC, 3);
GPIO_PIN_SOURCE(CAM_D4, PTC, 4);
GPIO_PIN_SOURCE(CAM_D5, PTC, 5);
GPIO_PIN_SOURCE(CAM_D6, PTC, 6);
GPIO_PIN_SOURCE(CAM_D7, PTC, 7);

GPIO_PIN_SOURCE(CAM_HSYNC,   PTD, 5);
GPIO_PIN_SOURCE(CAM_XCLK,    PTB, 0);

GPIO_PIN_SOURCE(CAM_OLED_RESET_N, PTA, 1);

GPIO_PIN_SOURCE(CAM_PWDN,    PTA, 4);

GPIO_PIN_SOURCE(POWEREN,    PTA, 2);
GPIO_PIN_SOURCE(DEBUG_UART, PTE, 16);
GPIO_PIN_SOURCE(SCK,        PTE, 17);
GPIO_PIN_SOURCE(MOSI,       PTE, 18);
GPIO_PIN_SOURCE(MISO,       PTE, 19);

GPIO_PIN_SOURCE(nV18_EN, PTA, 19);
GPIO_PIN_SOURCE(OLED_RST, PTA, 19);

#endif
