%% Init
rootPath = '../robot/simulator/worlds/';
if ~isdir(rootPath)
    mkdir(rootPath)
end

%% TwoBlocksOnePose
% One robot looking at one mat marker and two sides of each of two blocks 
worldName = 'TwoBlocksOnePose';
TestWorld = CozmoTestWorldCreator('WorldFile', ...
    fullfile(rootPath, ['visionTest_' worldName '.wbt']));

TestWorld.AddRobot('Name', 'Cozmo_1', ...
    'RobotPose', Pose([0 0 0], [80 0 20]), ...
    'HeadAngle', -10*pi/180);

TestWorld.AddBlock('BlockPose', Pose(pi/4*[0 0 1], [333 75 30]), ...
    'BlockProto', 'Block1x1', 'BlockType', 1, 'FrontFace', 'batteryMarker');

TestWorld.AddBlock('BlockPose', Pose(-pi/4*[0 0 1], [333 -75 30]), ...
    'BlockProto', 'Block1x1', 'BlockType', 2, 'FrontFace', 'bullseye');


%% MatPoseTest
% No blocks, just testing robot pose estimation as it moves around to
% different poses on a mat
worldName = 'MatPoseTest';
TestWorld = CozmoTestWorldCreator('WorldFile', ...
    fullfile(rootPath, ['visionTest_' worldName '.wbt']));

poses = { ...
    Pose(0*[0 0 1],      [-170 -260 18]), ...
    Pose(0.4927*[0 0 1], [-163  -95 18]), ...
    Pose(-.3927*[0 0 1], [-180  327 18]), ...
    Pose(3.5344*[0 0 1], [421    63 18]) ...
    };
    
headAngles = [-10 -15 -12 -10] * pi/180;

TestWorld.AddRobot('Name', 'Cozmo_1', ...
    'RobotPose', poses, ...
    'HeadAngle', headAngles);

