nnLibrary = VisionMarkerTrained.ExtractProbeValues( ...
  'addInversions', false,  ...
  'negativeImageDir', {}, ...
  'computeGradMag', false, ...
  'numPerturbations', 1, ...
  'perturbSigma', 0, ...
  'blurSigmas', [.005 0.015],  ...
  'imageSizes', 64, ...
  'exposures', [1 4],  ...
  'computeGradMagWeights', true, ...
  'blackPoint', 0, ...
  'boxFilterWidth', 0);
VisionMarkerTrained.GenerateNearestNeighborHeaderFiles('writeFiles', true, 'nnLibrary', nnLibrary);
VisionMarkerTrained.CreateTestImage;