// Autogenerated C# message buffer code.
// Source: comms/messaging/UiMessageDefinitionsG2U.clad
// Full command line: emitters/cozmo_CSharp_main_emitter.py -C src --output-file-override ../unity/Cozmo/Assets/Scripts/Channel/UiMessageDefinitionsG2U.cs comms/messaging/UiMessageDefinitionsG2U.clad

namespace Anki {

namespace Cozmo {

public class G2U_Ping
{
	private uint _counter; // uint_32

	public uint counter { get { return _counter; } set { _counter = value; } }


	/**** Constructors ****/

	public G2U_Ping()
	{
	}

	public G2U_Ping(uint counter)
	{
		this.counter = counter;
	}

	public G2U_Ping(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_Ping(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_counter = reader.ReadUInt32();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_counter);
	}

	public int Size 
	{
		get {
			return 4;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_Ping p = obj as G2U_Ping;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_Ping p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._counter.Equals(p._counter);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._counter.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotAvailable
{
	private uint _robotID; // uint_32

	public uint robotID { get { return _robotID; } set { _robotID = value; } }


	/**** Constructors ****/

	public G2U_RobotAvailable()
	{
	}

	public G2U_RobotAvailable(uint robotID)
	{
		this.robotID = robotID;
	}

	public G2U_RobotAvailable(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotAvailable(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
	}

	public int Size 
	{
		get {
			return 4;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotAvailable p = obj as G2U_RobotAvailable;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotAvailable p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			return hash;
		}
	}
}

public class G2U_UiDeviceAvailable
{
	private uint _deviceID; // uint_32

	public uint deviceID { get { return _deviceID; } set { _deviceID = value; } }


	/**** Constructors ****/

	public G2U_UiDeviceAvailable()
	{
	}

	public G2U_UiDeviceAvailable(uint deviceID)
	{
		this.deviceID = deviceID;
	}

	public G2U_UiDeviceAvailable(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_UiDeviceAvailable(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_deviceID = reader.ReadUInt32();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_deviceID);
	}

	public int Size 
	{
		get {
			return 4;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_UiDeviceAvailable p = obj as G2U_UiDeviceAvailable;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_UiDeviceAvailable p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._deviceID.Equals(p._deviceID);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._deviceID.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotConnected
{
	private uint _robotID; // uint_32
	private byte _successful; // uint_8

	public uint robotID { get { return _robotID; } set { _robotID = value; } }

	public byte successful { get { return _successful; } set { _successful = value; } }


	/**** Constructors ****/

	public G2U_RobotConnected()
	{
	}

	public G2U_RobotConnected(uint robotID,
		byte successful)
	{
		this.robotID = robotID;
		this.successful = successful;
	}

	public G2U_RobotConnected(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotConnected(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
		_successful = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
		writer.Write((byte)_successful);
	}

	public int Size 
	{
		get {
			return 5;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotConnected p = obj as G2U_RobotConnected;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotConnected p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID)
			&& this._successful.Equals(p._successful);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			hash = hash * 23 + this._successful.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotDisconnected
{
	private uint _robotID; // uint_32
	private float _timeSinceLastMsg_sec; // float_32

	public uint robotID { get { return _robotID; } set { _robotID = value; } }

	public float timeSinceLastMsg_sec { get { return _timeSinceLastMsg_sec; } set { _timeSinceLastMsg_sec = value; } }


	/**** Constructors ****/

	public G2U_RobotDisconnected()
	{
	}

	public G2U_RobotDisconnected(uint robotID,
		float timeSinceLastMsg_sec)
	{
		this.robotID = robotID;
		this.timeSinceLastMsg_sec = timeSinceLastMsg_sec;
	}

	public G2U_RobotDisconnected(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotDisconnected(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
		_timeSinceLastMsg_sec = reader.ReadSingle();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
		writer.Write((float)_timeSinceLastMsg_sec);
	}

	public int Size 
	{
		get {
			return 8;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotDisconnected p = obj as G2U_RobotDisconnected;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotDisconnected p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID)
			&& this._timeSinceLastMsg_sec.Equals(p._timeSinceLastMsg_sec);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			hash = hash * 23 + this._timeSinceLastMsg_sec.GetHashCode();
			return hash;
		}
	}
}

public class G2U_UiDeviceConnected
{
	private uint _deviceID; // uint_32
	private byte _successful; // uint_8

	public uint deviceID { get { return _deviceID; } set { _deviceID = value; } }

	public byte successful { get { return _successful; } set { _successful = value; } }


	/**** Constructors ****/

	public G2U_UiDeviceConnected()
	{
	}

	public G2U_UiDeviceConnected(uint deviceID,
		byte successful)
	{
		this.deviceID = deviceID;
		this.successful = successful;
	}

	public G2U_UiDeviceConnected(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_UiDeviceConnected(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_deviceID = reader.ReadUInt32();
		_successful = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_deviceID);
		writer.Write((byte)_successful);
	}

	public int Size 
	{
		get {
			return 5;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_UiDeviceConnected p = obj as G2U_UiDeviceConnected;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_UiDeviceConnected p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._deviceID.Equals(p._deviceID)
			&& this._successful.Equals(p._successful);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._deviceID.GetHashCode();
			hash = hash * 23 + this._successful.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotState
{
	private float _pose_x; // float_32
	private float _pose_y; // float_32
	private float _pose_z; // float_32
	private float _poseAngle_rad; // float_32
	private float _pose_quaternion0; // float_32
	private float _pose_quaternion1; // float_32
	private float _pose_quaternion2; // float_32
	private float _pose_quaternion3; // float_32
	private float _leftWheelSpeed_mmps; // float_32
	private float _rightWheelSpeed_mmps; // float_32
	private float _headAngle_rad; // float_32
	private float _liftHeight_mm; // float_32
	private float _batteryVoltage; // float_32
	private int _carryingObjectID; // int_32
	private int _carryingObjectOnTopID; // int_32
	private int _headTrackingObjectID; // int_32
	private byte _status; // uint_8
	private byte _robotID; // uint_8

	public float pose_x { get { return _pose_x; } set { _pose_x = value; } }

	public float pose_y { get { return _pose_y; } set { _pose_y = value; } }

	public float pose_z { get { return _pose_z; } set { _pose_z = value; } }

	public float poseAngle_rad { get { return _poseAngle_rad; } set { _poseAngle_rad = value; } }

	public float pose_quaternion0 { get { return _pose_quaternion0; } set { _pose_quaternion0 = value; } }

	public float pose_quaternion1 { get { return _pose_quaternion1; } set { _pose_quaternion1 = value; } }

	public float pose_quaternion2 { get { return _pose_quaternion2; } set { _pose_quaternion2 = value; } }

	public float pose_quaternion3 { get { return _pose_quaternion3; } set { _pose_quaternion3 = value; } }

	public float leftWheelSpeed_mmps { get { return _leftWheelSpeed_mmps; } set { _leftWheelSpeed_mmps = value; } }

	public float rightWheelSpeed_mmps { get { return _rightWheelSpeed_mmps; } set { _rightWheelSpeed_mmps = value; } }

	public float headAngle_rad { get { return _headAngle_rad; } set { _headAngle_rad = value; } }

	public float liftHeight_mm { get { return _liftHeight_mm; } set { _liftHeight_mm = value; } }

	public float batteryVoltage { get { return _batteryVoltage; } set { _batteryVoltage = value; } }

	public int carryingObjectID { get { return _carryingObjectID; } set { _carryingObjectID = value; } }

	public int carryingObjectOnTopID { get { return _carryingObjectOnTopID; } set { _carryingObjectOnTopID = value; } }

	public int headTrackingObjectID { get { return _headTrackingObjectID; } set { _headTrackingObjectID = value; } }

	public byte status { get { return _status; } set { _status = value; } }

	public byte robotID { get { return _robotID; } set { _robotID = value; } }


	/**** Constructors ****/

	public G2U_RobotState()
	{
	}

	public G2U_RobotState(float pose_x,
		float pose_y,
		float pose_z,
		float poseAngle_rad,
		float pose_quaternion0,
		float pose_quaternion1,
		float pose_quaternion2,
		float pose_quaternion3,
		float leftWheelSpeed_mmps,
		float rightWheelSpeed_mmps,
		float headAngle_rad,
		float liftHeight_mm,
		float batteryVoltage,
		int carryingObjectID,
		int carryingObjectOnTopID,
		int headTrackingObjectID,
		byte status,
		byte robotID)
	{
		this.pose_x = pose_x;
		this.pose_y = pose_y;
		this.pose_z = pose_z;
		this.poseAngle_rad = poseAngle_rad;
		this.pose_quaternion0 = pose_quaternion0;
		this.pose_quaternion1 = pose_quaternion1;
		this.pose_quaternion2 = pose_quaternion2;
		this.pose_quaternion3 = pose_quaternion3;
		this.leftWheelSpeed_mmps = leftWheelSpeed_mmps;
		this.rightWheelSpeed_mmps = rightWheelSpeed_mmps;
		this.headAngle_rad = headAngle_rad;
		this.liftHeight_mm = liftHeight_mm;
		this.batteryVoltage = batteryVoltage;
		this.carryingObjectID = carryingObjectID;
		this.carryingObjectOnTopID = carryingObjectOnTopID;
		this.headTrackingObjectID = headTrackingObjectID;
		this.status = status;
		this.robotID = robotID;
	}

	public G2U_RobotState(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotState(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_pose_x = reader.ReadSingle();
		_pose_y = reader.ReadSingle();
		_pose_z = reader.ReadSingle();
		_poseAngle_rad = reader.ReadSingle();
		_pose_quaternion0 = reader.ReadSingle();
		_pose_quaternion1 = reader.ReadSingle();
		_pose_quaternion2 = reader.ReadSingle();
		_pose_quaternion3 = reader.ReadSingle();
		_leftWheelSpeed_mmps = reader.ReadSingle();
		_rightWheelSpeed_mmps = reader.ReadSingle();
		_headAngle_rad = reader.ReadSingle();
		_liftHeight_mm = reader.ReadSingle();
		_batteryVoltage = reader.ReadSingle();
		_carryingObjectID = reader.ReadInt32();
		_carryingObjectOnTopID = reader.ReadInt32();
		_headTrackingObjectID = reader.ReadInt32();
		_status = reader.ReadByte();
		_robotID = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((float)_pose_x);
		writer.Write((float)_pose_y);
		writer.Write((float)_pose_z);
		writer.Write((float)_poseAngle_rad);
		writer.Write((float)_pose_quaternion0);
		writer.Write((float)_pose_quaternion1);
		writer.Write((float)_pose_quaternion2);
		writer.Write((float)_pose_quaternion3);
		writer.Write((float)_leftWheelSpeed_mmps);
		writer.Write((float)_rightWheelSpeed_mmps);
		writer.Write((float)_headAngle_rad);
		writer.Write((float)_liftHeight_mm);
		writer.Write((float)_batteryVoltage);
		writer.Write((int)_carryingObjectID);
		writer.Write((int)_carryingObjectOnTopID);
		writer.Write((int)_headTrackingObjectID);
		writer.Write((byte)_status);
		writer.Write((byte)_robotID);
	}

	public int Size 
	{
		get {
			return 66;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotState p = obj as G2U_RobotState;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotState p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._pose_x.Equals(p._pose_x)
			&& this._pose_y.Equals(p._pose_y)
			&& this._pose_z.Equals(p._pose_z)
			&& this._poseAngle_rad.Equals(p._poseAngle_rad)
			&& this._pose_quaternion0.Equals(p._pose_quaternion0)
			&& this._pose_quaternion1.Equals(p._pose_quaternion1)
			&& this._pose_quaternion2.Equals(p._pose_quaternion2)
			&& this._pose_quaternion3.Equals(p._pose_quaternion3)
			&& this._leftWheelSpeed_mmps.Equals(p._leftWheelSpeed_mmps)
			&& this._rightWheelSpeed_mmps.Equals(p._rightWheelSpeed_mmps)
			&& this._headAngle_rad.Equals(p._headAngle_rad)
			&& this._liftHeight_mm.Equals(p._liftHeight_mm)
			&& this._batteryVoltage.Equals(p._batteryVoltage)
			&& this._carryingObjectID.Equals(p._carryingObjectID)
			&& this._carryingObjectOnTopID.Equals(p._carryingObjectOnTopID)
			&& this._headTrackingObjectID.Equals(p._headTrackingObjectID)
			&& this._status.Equals(p._status)
			&& this._robotID.Equals(p._robotID);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._pose_x.GetHashCode();
			hash = hash * 23 + this._pose_y.GetHashCode();
			hash = hash * 23 + this._pose_z.GetHashCode();
			hash = hash * 23 + this._poseAngle_rad.GetHashCode();
			hash = hash * 23 + this._pose_quaternion0.GetHashCode();
			hash = hash * 23 + this._pose_quaternion1.GetHashCode();
			hash = hash * 23 + this._pose_quaternion2.GetHashCode();
			hash = hash * 23 + this._pose_quaternion3.GetHashCode();
			hash = hash * 23 + this._leftWheelSpeed_mmps.GetHashCode();
			hash = hash * 23 + this._rightWheelSpeed_mmps.GetHashCode();
			hash = hash * 23 + this._headAngle_rad.GetHashCode();
			hash = hash * 23 + this._liftHeight_mm.GetHashCode();
			hash = hash * 23 + this._batteryVoltage.GetHashCode();
			hash = hash * 23 + this._carryingObjectID.GetHashCode();
			hash = hash * 23 + this._carryingObjectOnTopID.GetHashCode();
			hash = hash * 23 + this._headTrackingObjectID.GetHashCode();
			hash = hash * 23 + this._status.GetHashCode();
			hash = hash * 23 + this._robotID.GetHashCode();
			return hash;
		}
	}
}

public class G2U_ImageChunk
{
	private uint _imageId; // uint_32
	private uint _frameTimeStamp; // uint_32
	private ushort _nrows; // uint_16
	private ushort _ncols; // uint_16
	private ushort _chunkSize; // uint_16
	private byte _imageEncoding; // uint_8
	private byte _imageChunkCount; // uint_8
	private byte _chunkId; // uint_8
	private byte[] _data; // uint_8[1400]

	public uint imageId { get { return _imageId; } set { _imageId = value; } }

	public uint frameTimeStamp { get { return _frameTimeStamp; } set { _frameTimeStamp = value; } }

	public ushort nrows { get { return _nrows; } set { _nrows = value; } }

	public ushort ncols { get { return _ncols; } set { _ncols = value; } }

	public ushort chunkSize { get { return _chunkSize; } set { _chunkSize = value; } }

	public byte imageEncoding { get { return _imageEncoding; } set { _imageEncoding = value; } }

	public byte imageChunkCount { get { return _imageChunkCount; } set { _imageChunkCount = value; } }

	public byte chunkId { get { return _chunkId; } set { _chunkId = value; } }

	public byte[] data
	{
		get {
			return _data;
		}
		set {
			if (value == null) {
				throw new System.ArgumentException("data fixed-length array is null. Must have a length of 1400.", "value");
			}
			if (value.Length != 1400) {
				throw new System.ArgumentException("data fixed-length array is the wrong size. Must have a length of 1400.", "value");
			}
			_data = value;
		}
	}


	/**** Constructors ****/

	public G2U_ImageChunk()
	{
		this.data = new byte[1400];
	}

	public G2U_ImageChunk(uint imageId,
		uint frameTimeStamp,
		ushort nrows,
		ushort ncols,
		ushort chunkSize,
		byte imageEncoding,
		byte imageChunkCount,
		byte chunkId,
		byte[] data)
	{
		this.imageId = imageId;
		this.frameTimeStamp = frameTimeStamp;
		this.nrows = nrows;
		this.ncols = ncols;
		this.chunkSize = chunkSize;
		this.imageEncoding = imageEncoding;
		this.imageChunkCount = imageChunkCount;
		this.chunkId = chunkId;
		this.data = data;
	}

	public G2U_ImageChunk(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_ImageChunk(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_imageId = reader.ReadUInt32();
		_frameTimeStamp = reader.ReadUInt32();
		_nrows = reader.ReadUInt16();
		_ncols = reader.ReadUInt16();
		_chunkSize = reader.ReadUInt16();
		_imageEncoding = reader.ReadByte();
		_imageChunkCount = reader.ReadByte();
		_chunkId = reader.ReadByte();
		_data = new byte[1400];
		for (int i = 0; i < 1400; ++i) {
			_data[i] = reader.ReadByte();
		}
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_imageId);
		writer.Write((uint)_frameTimeStamp);
		writer.Write((ushort)_nrows);
		writer.Write((ushort)_ncols);
		writer.Write((ushort)_chunkSize);
		writer.Write((byte)_imageEncoding);
		writer.Write((byte)_imageChunkCount);
		writer.Write((byte)_chunkId);
		for (int i = 0; i < 1400; ++i) {
			writer.Write((byte)_data[i]);
		}
	}

	public int Size 
	{
		get {
			return 1417;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_ImageChunk p = obj as G2U_ImageChunk;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_ImageChunk p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._imageId.Equals(p._imageId)
			&& this._frameTimeStamp.Equals(p._frameTimeStamp)
			&& this._nrows.Equals(p._nrows)
			&& this._ncols.Equals(p._ncols)
			&& this._chunkSize.Equals(p._chunkSize)
			&& this._imageEncoding.Equals(p._imageEncoding)
			&& this._imageChunkCount.Equals(p._imageChunkCount)
			&& this._chunkId.Equals(p._chunkId)
			&& ArrayEquals<byte>(this._data,p._data);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._imageId.GetHashCode();
			hash = hash * 23 + this._frameTimeStamp.GetHashCode();
			hash = hash * 23 + this._nrows.GetHashCode();
			hash = hash * 23 + this._ncols.GetHashCode();
			hash = hash * 23 + this._chunkSize.GetHashCode();
			hash = hash * 23 + this._imageEncoding.GetHashCode();
			hash = hash * 23 + this._imageChunkCount.GetHashCode();
			hash = hash * 23 + this._chunkId.GetHashCode();
			hash = hash * 23 + this._data.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotObservedObject
{
	private uint _robotID; // uint_32
	private uint _objectFamily; // uint_32
	private uint _objectType; // uint_32
	private int _objectID; // int_32
	private float _img_topLeft_x; // float_32
	private float _img_topLeft_y; // float_32
	private float _img_width; // float_32
	private float _img_height; // float_32
	private float _world_x; // float_32
	private float _world_y; // float_32
	private float _world_z; // float_32
	private float _quaternion0; // float_32
	private float _quaternion1; // float_32
	private float _quaternion2; // float_32
	private float _quaternion3; // float_32
	private byte _markersVisible; // uint_8
	private byte _isActive; // uint_8

	public uint robotID { get { return _robotID; } set { _robotID = value; } }

	public uint objectFamily { get { return _objectFamily; } set { _objectFamily = value; } }

	public uint objectType { get { return _objectType; } set { _objectType = value; } }

	public int objectID { get { return _objectID; } set { _objectID = value; } }

	public float img_topLeft_x { get { return _img_topLeft_x; } set { _img_topLeft_x = value; } }

	public float img_topLeft_y { get { return _img_topLeft_y; } set { _img_topLeft_y = value; } }

	public float img_width { get { return _img_width; } set { _img_width = value; } }

	public float img_height { get { return _img_height; } set { _img_height = value; } }

	public float world_x { get { return _world_x; } set { _world_x = value; } }

	public float world_y { get { return _world_y; } set { _world_y = value; } }

	public float world_z { get { return _world_z; } set { _world_z = value; } }

	public float quaternion0 { get { return _quaternion0; } set { _quaternion0 = value; } }

	public float quaternion1 { get { return _quaternion1; } set { _quaternion1 = value; } }

	public float quaternion2 { get { return _quaternion2; } set { _quaternion2 = value; } }

	public float quaternion3 { get { return _quaternion3; } set { _quaternion3 = value; } }

	public byte markersVisible { get { return _markersVisible; } set { _markersVisible = value; } }

	public byte isActive { get { return _isActive; } set { _isActive = value; } }


	/**** Constructors ****/

	public G2U_RobotObservedObject()
	{
	}

	public G2U_RobotObservedObject(uint robotID,
		uint objectFamily,
		uint objectType,
		int objectID,
		float img_topLeft_x,
		float img_topLeft_y,
		float img_width,
		float img_height,
		float world_x,
		float world_y,
		float world_z,
		float quaternion0,
		float quaternion1,
		float quaternion2,
		float quaternion3,
		byte markersVisible,
		byte isActive)
	{
		this.robotID = robotID;
		this.objectFamily = objectFamily;
		this.objectType = objectType;
		this.objectID = objectID;
		this.img_topLeft_x = img_topLeft_x;
		this.img_topLeft_y = img_topLeft_y;
		this.img_width = img_width;
		this.img_height = img_height;
		this.world_x = world_x;
		this.world_y = world_y;
		this.world_z = world_z;
		this.quaternion0 = quaternion0;
		this.quaternion1 = quaternion1;
		this.quaternion2 = quaternion2;
		this.quaternion3 = quaternion3;
		this.markersVisible = markersVisible;
		this.isActive = isActive;
	}

	public G2U_RobotObservedObject(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotObservedObject(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
		_objectFamily = reader.ReadUInt32();
		_objectType = reader.ReadUInt32();
		_objectID = reader.ReadInt32();
		_img_topLeft_x = reader.ReadSingle();
		_img_topLeft_y = reader.ReadSingle();
		_img_width = reader.ReadSingle();
		_img_height = reader.ReadSingle();
		_world_x = reader.ReadSingle();
		_world_y = reader.ReadSingle();
		_world_z = reader.ReadSingle();
		_quaternion0 = reader.ReadSingle();
		_quaternion1 = reader.ReadSingle();
		_quaternion2 = reader.ReadSingle();
		_quaternion3 = reader.ReadSingle();
		_markersVisible = reader.ReadByte();
		_isActive = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
		writer.Write((uint)_objectFamily);
		writer.Write((uint)_objectType);
		writer.Write((int)_objectID);
		writer.Write((float)_img_topLeft_x);
		writer.Write((float)_img_topLeft_y);
		writer.Write((float)_img_width);
		writer.Write((float)_img_height);
		writer.Write((float)_world_x);
		writer.Write((float)_world_y);
		writer.Write((float)_world_z);
		writer.Write((float)_quaternion0);
		writer.Write((float)_quaternion1);
		writer.Write((float)_quaternion2);
		writer.Write((float)_quaternion3);
		writer.Write((byte)_markersVisible);
		writer.Write((byte)_isActive);
	}

	public int Size 
	{
		get {
			return 62;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotObservedObject p = obj as G2U_RobotObservedObject;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotObservedObject p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID)
			&& this._objectFamily.Equals(p._objectFamily)
			&& this._objectType.Equals(p._objectType)
			&& this._objectID.Equals(p._objectID)
			&& this._img_topLeft_x.Equals(p._img_topLeft_x)
			&& this._img_topLeft_y.Equals(p._img_topLeft_y)
			&& this._img_width.Equals(p._img_width)
			&& this._img_height.Equals(p._img_height)
			&& this._world_x.Equals(p._world_x)
			&& this._world_y.Equals(p._world_y)
			&& this._world_z.Equals(p._world_z)
			&& this._quaternion0.Equals(p._quaternion0)
			&& this._quaternion1.Equals(p._quaternion1)
			&& this._quaternion2.Equals(p._quaternion2)
			&& this._quaternion3.Equals(p._quaternion3)
			&& this._markersVisible.Equals(p._markersVisible)
			&& this._isActive.Equals(p._isActive);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			hash = hash * 23 + this._objectFamily.GetHashCode();
			hash = hash * 23 + this._objectType.GetHashCode();
			hash = hash * 23 + this._objectID.GetHashCode();
			hash = hash * 23 + this._img_topLeft_x.GetHashCode();
			hash = hash * 23 + this._img_topLeft_y.GetHashCode();
			hash = hash * 23 + this._img_width.GetHashCode();
			hash = hash * 23 + this._img_height.GetHashCode();
			hash = hash * 23 + this._world_x.GetHashCode();
			hash = hash * 23 + this._world_y.GetHashCode();
			hash = hash * 23 + this._world_z.GetHashCode();
			hash = hash * 23 + this._quaternion0.GetHashCode();
			hash = hash * 23 + this._quaternion1.GetHashCode();
			hash = hash * 23 + this._quaternion2.GetHashCode();
			hash = hash * 23 + this._quaternion3.GetHashCode();
			hash = hash * 23 + this._markersVisible.GetHashCode();
			hash = hash * 23 + this._isActive.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotObservedNothing
{
	private uint _robotID; // uint_32

	public uint robotID { get { return _robotID; } set { _robotID = value; } }


	/**** Constructors ****/

	public G2U_RobotObservedNothing()
	{
	}

	public G2U_RobotObservedNothing(uint robotID)
	{
		this.robotID = robotID;
	}

	public G2U_RobotObservedNothing(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotObservedNothing(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
	}

	public int Size 
	{
		get {
			return 4;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotObservedNothing p = obj as G2U_RobotObservedNothing;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotObservedNothing p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotDeletedObject
{
	private uint _robotID; // uint_32
	private uint _objectID; // uint_32

	public uint robotID { get { return _robotID; } set { _robotID = value; } }

	public uint objectID { get { return _objectID; } set { _objectID = value; } }


	/**** Constructors ****/

	public G2U_RobotDeletedObject()
	{
	}

	public G2U_RobotDeletedObject(uint robotID,
		uint objectID)
	{
		this.robotID = robotID;
		this.objectID = objectID;
	}

	public G2U_RobotDeletedObject(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotDeletedObject(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
		_objectID = reader.ReadUInt32();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
		writer.Write((uint)_objectID);
	}

	public int Size 
	{
		get {
			return 8;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotDeletedObject p = obj as G2U_RobotDeletedObject;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotDeletedObject p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID)
			&& this._objectID.Equals(p._objectID);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			hash = hash * 23 + this._objectID.GetHashCode();
			return hash;
		}
	}
}

public class G2U_DeviceDetectedVisionMarker
{
	private uint _markerType; // uint_32
	private float _x_upperLeft; // float_32
	private float _y_upperLeft; // float_32
	private float _x_lowerLeft; // float_32
	private float _y_lowerLeft; // float_32
	private float _x_upperRight; // float_32
	private float _y_upperRight; // float_32
	private float _x_lowerRight; // float_32
	private float _y_lowerRight; // float_32

	public uint markerType { get { return _markerType; } set { _markerType = value; } }

	public float x_upperLeft { get { return _x_upperLeft; } set { _x_upperLeft = value; } }

	public float y_upperLeft { get { return _y_upperLeft; } set { _y_upperLeft = value; } }

	public float x_lowerLeft { get { return _x_lowerLeft; } set { _x_lowerLeft = value; } }

	public float y_lowerLeft { get { return _y_lowerLeft; } set { _y_lowerLeft = value; } }

	public float x_upperRight { get { return _x_upperRight; } set { _x_upperRight = value; } }

	public float y_upperRight { get { return _y_upperRight; } set { _y_upperRight = value; } }

	public float x_lowerRight { get { return _x_lowerRight; } set { _x_lowerRight = value; } }

	public float y_lowerRight { get { return _y_lowerRight; } set { _y_lowerRight = value; } }


	/**** Constructors ****/

	public G2U_DeviceDetectedVisionMarker()
	{
	}

	public G2U_DeviceDetectedVisionMarker(uint markerType,
		float x_upperLeft,
		float y_upperLeft,
		float x_lowerLeft,
		float y_lowerLeft,
		float x_upperRight,
		float y_upperRight,
		float x_lowerRight,
		float y_lowerRight)
	{
		this.markerType = markerType;
		this.x_upperLeft = x_upperLeft;
		this.y_upperLeft = y_upperLeft;
		this.x_lowerLeft = x_lowerLeft;
		this.y_lowerLeft = y_lowerLeft;
		this.x_upperRight = x_upperRight;
		this.y_upperRight = y_upperRight;
		this.x_lowerRight = x_lowerRight;
		this.y_lowerRight = y_lowerRight;
	}

	public G2U_DeviceDetectedVisionMarker(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_DeviceDetectedVisionMarker(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_markerType = reader.ReadUInt32();
		_x_upperLeft = reader.ReadSingle();
		_y_upperLeft = reader.ReadSingle();
		_x_lowerLeft = reader.ReadSingle();
		_y_lowerLeft = reader.ReadSingle();
		_x_upperRight = reader.ReadSingle();
		_y_upperRight = reader.ReadSingle();
		_x_lowerRight = reader.ReadSingle();
		_y_lowerRight = reader.ReadSingle();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_markerType);
		writer.Write((float)_x_upperLeft);
		writer.Write((float)_y_upperLeft);
		writer.Write((float)_x_lowerLeft);
		writer.Write((float)_y_lowerLeft);
		writer.Write((float)_x_upperRight);
		writer.Write((float)_y_upperRight);
		writer.Write((float)_x_lowerRight);
		writer.Write((float)_y_lowerRight);
	}

	public int Size 
	{
		get {
			return 36;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_DeviceDetectedVisionMarker p = obj as G2U_DeviceDetectedVisionMarker;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_DeviceDetectedVisionMarker p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._markerType.Equals(p._markerType)
			&& this._x_upperLeft.Equals(p._x_upperLeft)
			&& this._y_upperLeft.Equals(p._y_upperLeft)
			&& this._x_lowerLeft.Equals(p._x_lowerLeft)
			&& this._y_lowerLeft.Equals(p._y_lowerLeft)
			&& this._x_upperRight.Equals(p._x_upperRight)
			&& this._y_upperRight.Equals(p._y_upperRight)
			&& this._x_lowerRight.Equals(p._x_lowerRight)
			&& this._y_lowerRight.Equals(p._y_lowerRight);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._markerType.GetHashCode();
			hash = hash * 23 + this._x_upperLeft.GetHashCode();
			hash = hash * 23 + this._y_upperLeft.GetHashCode();
			hash = hash * 23 + this._x_lowerLeft.GetHashCode();
			hash = hash * 23 + this._y_lowerLeft.GetHashCode();
			hash = hash * 23 + this._x_upperRight.GetHashCode();
			hash = hash * 23 + this._y_upperRight.GetHashCode();
			hash = hash * 23 + this._x_lowerRight.GetHashCode();
			hash = hash * 23 + this._y_lowerRight.GetHashCode();
			return hash;
		}
	}
}

public class G2U_RobotCompletedAction
{
	private uint _robotID; // uint_32
	private int _actionType; // int_32
	private byte _success; // uint_8

	public uint robotID { get { return _robotID; } set { _robotID = value; } }

	public int actionType { get { return _actionType; } set { _actionType = value; } }

	public byte success { get { return _success; } set { _success = value; } }


	/**** Constructors ****/

	public G2U_RobotCompletedAction()
	{
	}

	public G2U_RobotCompletedAction(uint robotID,
		int actionType,
		byte success)
	{
		this.robotID = robotID;
		this.actionType = actionType;
		this.success = success;
	}

	public G2U_RobotCompletedAction(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_RobotCompletedAction(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		_robotID = reader.ReadUInt32();
		_actionType = reader.ReadInt32();
		_success = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		writer.Write((uint)_robotID);
		writer.Write((int)_actionType);
		writer.Write((byte)_success);
	}

	public int Size 
	{
		get {
			return 9;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_RobotCompletedAction p = obj as G2U_RobotCompletedAction;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_RobotCompletedAction p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._robotID.Equals(p._robotID)
			&& this._actionType.Equals(p._actionType)
			&& this._success.Equals(p._success);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._robotID.GetHashCode();
			hash = hash * 23 + this._actionType.GetHashCode();
			hash = hash * 23 + this._success.GetHashCode();
			return hash;
		}
	}
}

public class G2U_PlaySound
{
	private string _soundFilename; // string[uint_8]
	private byte _numLoops; // uint_8
	private byte _volume; // uint_8

	public string soundFilename
	{
		get {
			return _soundFilename;
		}
		set {
			if (!string.IsNullOrEmpty(value) && System.Text.Encoding.UTF8.GetByteCount(value) > 255) {
				throw new System.ArgumentException("soundFilename string is too long. Must decode to less than or equal to 255 bytes.", "value");
			}
			_soundFilename = value;
		}
	}

	public byte numLoops { get { return _numLoops; } set { _numLoops = value; } }

	public byte volume { get { return _volume; } set { _volume = value; } }


	/**** Constructors ****/

	public G2U_PlaySound()
	{
	}

	public G2U_PlaySound(string soundFilename,
		byte numLoops,
		byte volume)
	{
		this.soundFilename = soundFilename;
		this.numLoops = numLoops;
		this.volume = volume;
	}

	public G2U_PlaySound(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_PlaySound(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Unpack(reader);
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
		int _soundFilename_length = (int)reader.ReadByte();
		byte[] _soundFilename_bytes = reader.ReadBytes(_soundFilename_length);
		_soundFilename = System.Text.Encoding.UTF8.GetString(_soundFilename_bytes);
		_numLoops = reader.ReadByte();
		_volume = reader.ReadByte();
	}

	public void Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		Pack(writer);
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
		if (_soundFilename != null) {
			byte[] _soundFilename_bytes = System.Text.Encoding.UTF8.GetBytes(_soundFilename);
			writer.Write((byte)_soundFilename_bytes.Length);
			writer.Write(_soundFilename_bytes);
		}
		writer.Write((byte)_numLoops);
		writer.Write((byte)_volume);
	}

	public int Size 
	{
		get {
			int result = 0;
			result += 1; // uint_8
			if (soundFilename != null) {
				result += System.Text.Encoding.UTF8.GetByteCount(soundFilename);
			}
			result += 1; // uint_8
			result += 1; // uint_8
			return result;
		}
	}

	public static bool ArrayEquals<T>(T[] a1, T[] a2) {
		if (ReferenceEquals(a1, a2))
			return true;

		if (a1 == null || a2 == null)
			return false;

		if (a1.Length != a2.Length)
			return false;

		for (int i = 0; i < a1.Length; i++)
		{
			if (!a1[i].Equals(a2[i])) {
				return false;
			}
		}
		return true;
	}

	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_PlaySound p = obj as G2U_PlaySound;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_PlaySound p)
	{
		if ((object) p == null)
		{
			return false;
		}

		return this._soundFilename.Equals(p._soundFilename)
			&& this._numLoops.Equals(p._numLoops)
			&& this._volume.Equals(p._volume);
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._soundFilename.GetHashCode();
			hash = hash * 23 + this._numLoops.GetHashCode();
			hash = hash * 23 + this._volume.GetHashCode();
			return hash;
		}
	}
}

public class G2U_StopSound
{
	/**** Constructors ****/

	public G2U_StopSound()
	{
	}

	public G2U_StopSound(System.IO.Stream stream)
	{
		Unpack(stream);
	}

	public G2U_StopSound(System.IO.BinaryReader reader)
	{
		Unpack(reader);
	}

	public void Unpack(System.IO.Stream stream)
	{
	}

	public void Unpack(System.IO.BinaryReader reader)
	{
	}

	public void Pack(System.IO.Stream stream)
	{
	}

	public void Pack(System.IO.BinaryWriter writer)
	{
	}

	public int Size 
	{
		get {
			return 0;
		}
	}

}

public class G2U_Message {
	public enum Tag {
		Ping,	//0
		RobotAvailable,	//1
		UiDeviceAvailable,	//2
		RobotConnected,	//3
		RobotDisconnected,	//4
		UiDeviceConnected,	//5
		RobotState,	//6
		ImageChunk,	//7
		RobotObservedObject,	//8
		RobotObservedNothing,	//9
		RobotDeletedObject,	//10
		DeviceDetectedVisionMarker,	//11
		RobotCompletedAction,	//12
		PlaySound,	//13
		StopSound,	//14
		INVALID
	};

	private Tag _tag = Tag.INVALID;

	public Tag GetTag() { return _tag; }

	private object _state = null;

	public Anki.Cozmo.G2U_Ping Ping
	{
		get {
			if (_tag != Tag.Ping) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"Ping\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_Ping)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.Ping : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotAvailable RobotAvailable
	{
		get {
			if (_tag != Tag.RobotAvailable) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotAvailable\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotAvailable)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotAvailable : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_UiDeviceAvailable UiDeviceAvailable
	{
		get {
			if (_tag != Tag.UiDeviceAvailable) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"UiDeviceAvailable\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_UiDeviceAvailable)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.UiDeviceAvailable : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotConnected RobotConnected
	{
		get {
			if (_tag != Tag.RobotConnected) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotConnected\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotConnected)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotConnected : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotDisconnected RobotDisconnected
	{
		get {
			if (_tag != Tag.RobotDisconnected) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotDisconnected\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotDisconnected)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotDisconnected : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_UiDeviceConnected UiDeviceConnected
	{
		get {
			if (_tag != Tag.UiDeviceConnected) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"UiDeviceConnected\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_UiDeviceConnected)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.UiDeviceConnected : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotState RobotState
	{
		get {
			if (_tag != Tag.RobotState) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotState\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotState)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotState : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_ImageChunk ImageChunk
	{
		get {
			if (_tag != Tag.ImageChunk) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"ImageChunk\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_ImageChunk)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.ImageChunk : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotObservedObject RobotObservedObject
	{
		get {
			if (_tag != Tag.RobotObservedObject) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotObservedObject\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotObservedObject)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotObservedObject : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotObservedNothing RobotObservedNothing
	{
		get {
			if (_tag != Tag.RobotObservedNothing) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotObservedNothing\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotObservedNothing)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotObservedNothing : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotDeletedObject RobotDeletedObject
	{
		get {
			if (_tag != Tag.RobotDeletedObject) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotDeletedObject\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotDeletedObject)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotDeletedObject : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_DeviceDetectedVisionMarker DeviceDetectedVisionMarker
	{
		get {
			if (_tag != Tag.DeviceDetectedVisionMarker) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"DeviceDetectedVisionMarker\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_DeviceDetectedVisionMarker)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.DeviceDetectedVisionMarker : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_RobotCompletedAction RobotCompletedAction
	{
		get {
			if (_tag != Tag.RobotCompletedAction) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"RobotCompletedAction\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_RobotCompletedAction)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.RobotCompletedAction : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_PlaySound PlaySound
	{
		get {
			if (_tag != Tag.PlaySound) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"PlaySound\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_PlaySound)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.PlaySound : Tag.INVALID;
			_state = value;
		}
	}

	public Anki.Cozmo.G2U_StopSound StopSound
	{
		get {
			if (_tag != Tag.StopSound) {
				throw new System.InvalidOperationException(string.Format(
					"Cannot access union member \"StopSound\" when a value of type {0} is stored.",
					_tag.ToString()));
			}
			return (Anki.Cozmo.G2U_StopSound)this._state;
		}
		
		set {
			_tag = (value != null) ? Tag.StopSound : Tag.INVALID;
			_state = value;
		}
	}

	public System.IO.Stream Unpack(System.IO.Stream stream)
	{
		System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
		Tag newTag = Tag.INVALID;
		newTag = (Tag)reader.ReadByte();
		switch(newTag) {
		case Tag.Ping:
			_state = new Anki.Cozmo.G2U_Ping(reader);
			break;
		case Tag.RobotAvailable:
			_state = new Anki.Cozmo.G2U_RobotAvailable(reader);
			break;
		case Tag.UiDeviceAvailable:
			_state = new Anki.Cozmo.G2U_UiDeviceAvailable(reader);
			break;
		case Tag.RobotConnected:
			_state = new Anki.Cozmo.G2U_RobotConnected(reader);
			break;
		case Tag.RobotDisconnected:
			_state = new Anki.Cozmo.G2U_RobotDisconnected(reader);
			break;
		case Tag.UiDeviceConnected:
			_state = new Anki.Cozmo.G2U_UiDeviceConnected(reader);
			break;
		case Tag.RobotState:
			_state = new Anki.Cozmo.G2U_RobotState(reader);
			break;
		case Tag.ImageChunk:
			_state = new Anki.Cozmo.G2U_ImageChunk(reader);
			break;
		case Tag.RobotObservedObject:
			_state = new Anki.Cozmo.G2U_RobotObservedObject(reader);
			break;
		case Tag.RobotObservedNothing:
			_state = new Anki.Cozmo.G2U_RobotObservedNothing(reader);
			break;
		case Tag.RobotDeletedObject:
			_state = new Anki.Cozmo.G2U_RobotDeletedObject(reader);
			break;
		case Tag.DeviceDetectedVisionMarker:
			_state = new Anki.Cozmo.G2U_DeviceDetectedVisionMarker(reader);
			break;
		case Tag.RobotCompletedAction:
			_state = new Anki.Cozmo.G2U_RobotCompletedAction(reader);
			break;
		case Tag.PlaySound:
			_state = new Anki.Cozmo.G2U_PlaySound(reader);
			break;
		case Tag.StopSound:
			_state = new Anki.Cozmo.G2U_StopSound(reader);
			break;
		default:
			break;
		}
		_tag = newTag;
		return stream;
	}

	public System.IO.Stream Pack(System.IO.Stream stream)
	{
		System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
		writer.Write((byte)GetTag());
		switch(GetTag()) {
		case Tag.Ping:
			Ping.Pack(writer);
			break;
		case Tag.RobotAvailable:
			RobotAvailable.Pack(writer);
			break;
		case Tag.UiDeviceAvailable:
			UiDeviceAvailable.Pack(writer);
			break;
		case Tag.RobotConnected:
			RobotConnected.Pack(writer);
			break;
		case Tag.RobotDisconnected:
			RobotDisconnected.Pack(writer);
			break;
		case Tag.UiDeviceConnected:
			UiDeviceConnected.Pack(writer);
			break;
		case Tag.RobotState:
			RobotState.Pack(writer);
			break;
		case Tag.ImageChunk:
			ImageChunk.Pack(writer);
			break;
		case Tag.RobotObservedObject:
			RobotObservedObject.Pack(writer);
			break;
		case Tag.RobotObservedNothing:
			RobotObservedNothing.Pack(writer);
			break;
		case Tag.RobotDeletedObject:
			RobotDeletedObject.Pack(writer);
			break;
		case Tag.DeviceDetectedVisionMarker:
			DeviceDetectedVisionMarker.Pack(writer);
			break;
		case Tag.RobotCompletedAction:
			RobotCompletedAction.Pack(writer);
			break;
		case Tag.PlaySound:
			PlaySound.Pack(writer);
			break;
		case Tag.StopSound:
			StopSound.Pack(writer);
			break;
		default:
			break;
		}
		return stream;
	}

	public int Size
	{
		get {
			int result = 1; // tag = uint_8
			switch(GetTag()) {
			case Tag.Ping:
				result += Ping.Size;
				break;
			case Tag.RobotAvailable:
				result += RobotAvailable.Size;
				break;
			case Tag.UiDeviceAvailable:
				result += UiDeviceAvailable.Size;
				break;
			case Tag.RobotConnected:
				result += RobotConnected.Size;
				break;
			case Tag.RobotDisconnected:
				result += RobotDisconnected.Size;
				break;
			case Tag.UiDeviceConnected:
				result += UiDeviceConnected.Size;
				break;
			case Tag.RobotState:
				result += RobotState.Size;
				break;
			case Tag.ImageChunk:
				result += ImageChunk.Size;
				break;
			case Tag.RobotObservedObject:
				result += RobotObservedObject.Size;
				break;
			case Tag.RobotObservedNothing:
				result += RobotObservedNothing.Size;
				break;
			case Tag.RobotDeletedObject:
				result += RobotDeletedObject.Size;
				break;
			case Tag.DeviceDetectedVisionMarker:
				result += DeviceDetectedVisionMarker.Size;
				break;
			case Tag.RobotCompletedAction:
				result += RobotCompletedAction.Size;
				break;
			case Tag.PlaySound:
				result += PlaySound.Size;
				break;
			case Tag.StopSound:
				result += StopSound.Size;
				break;
			default:
				return 0;
			}
			return result;
		}
	}
	public override bool Equals(System.Object obj)
	{
		if (obj == null)
		{
			return false;
		}

		G2U_Message p = obj as G2U_Message;
		if ((System.Object) p == null)
		{
			return false;
		}

		return this.Equals(p);
	}

	public bool Equals(G2U_Message p)
	{
		if ((object) p == null)
		{
			return false;
		}

		if (!this._tag.Equals(p._tag))
		{
			return false;
		}

		switch(GetTag()) {

		case Tag.Ping:
			return this.Ping.Equals(p.Ping);
		case Tag.RobotAvailable:
			return this.RobotAvailable.Equals(p.RobotAvailable);
		case Tag.UiDeviceAvailable:
			return this.UiDeviceAvailable.Equals(p.UiDeviceAvailable);
		case Tag.RobotConnected:
			return this.RobotConnected.Equals(p.RobotConnected);
		case Tag.RobotDisconnected:
			return this.RobotDisconnected.Equals(p.RobotDisconnected);
		case Tag.UiDeviceConnected:
			return this.UiDeviceConnected.Equals(p.UiDeviceConnected);
		case Tag.RobotState:
			return this.RobotState.Equals(p.RobotState);
		case Tag.ImageChunk:
			return this.ImageChunk.Equals(p.ImageChunk);
		case Tag.RobotObservedObject:
			return this.RobotObservedObject.Equals(p.RobotObservedObject);
		case Tag.RobotObservedNothing:
			return this.RobotObservedNothing.Equals(p.RobotObservedNothing);
		case Tag.RobotDeletedObject:
			return this.RobotDeletedObject.Equals(p.RobotDeletedObject);
		case Tag.DeviceDetectedVisionMarker:
			return this.DeviceDetectedVisionMarker.Equals(p.DeviceDetectedVisionMarker);
		case Tag.RobotCompletedAction:
			return this.RobotCompletedAction.Equals(p.RobotCompletedAction);
		case Tag.PlaySound:
			return this.PlaySound.Equals(p.PlaySound);
		case Tag.StopSound:
			return this.StopSound.Equals(p.StopSound);
		default:
			return false;
		}
	}

	public override int GetHashCode()
	{
		unchecked
		{
			int hash = 17;
			hash = hash * 23 + this._tag.GetHashCode();
			switch(GetTag()) {
			case Tag.Ping:
				hash = hash * 23 + this.Ping.GetHashCode();
				break;
			case Tag.RobotAvailable:
				hash = hash * 23 + this.RobotAvailable.GetHashCode();
				break;
			case Tag.UiDeviceAvailable:
				hash = hash * 23 + this.UiDeviceAvailable.GetHashCode();
				break;
			case Tag.RobotConnected:
				hash = hash * 23 + this.RobotConnected.GetHashCode();
				break;
			case Tag.RobotDisconnected:
				hash = hash * 23 + this.RobotDisconnected.GetHashCode();
				break;
			case Tag.UiDeviceConnected:
				hash = hash * 23 + this.UiDeviceConnected.GetHashCode();
				break;
			case Tag.RobotState:
				hash = hash * 23 + this.RobotState.GetHashCode();
				break;
			case Tag.ImageChunk:
				hash = hash * 23 + this.ImageChunk.GetHashCode();
				break;
			case Tag.RobotObservedObject:
				hash = hash * 23 + this.RobotObservedObject.GetHashCode();
				break;
			case Tag.RobotObservedNothing:
				hash = hash * 23 + this.RobotObservedNothing.GetHashCode();
				break;
			case Tag.RobotDeletedObject:
				hash = hash * 23 + this.RobotDeletedObject.GetHashCode();
				break;
			case Tag.DeviceDetectedVisionMarker:
				hash = hash * 23 + this.DeviceDetectedVisionMarker.GetHashCode();
				break;
			case Tag.RobotCompletedAction:
				hash = hash * 23 + this.RobotCompletedAction.GetHashCode();
				break;
			case Tag.PlaySound:
				hash = hash * 23 + this.PlaySound.GetHashCode();
				break;
			case Tag.StopSound:
				hash = hash * 23 + this.StopSound.GetHashCode();
				break;
			default:
				break;
			}
			return hash;
		}
	}
}

} // namespace Cozmo

} // namespace Anki

