FROM victor
ARG USER
ARG UID
ARG VIC_DIR

# Actually use bash
RUN ln -sf /bin/bash /bin/sh

WORKDIR ${VIC_DIR}
RUN useradd -Ums /bin/bash -u ${UID} ${USER}
ENTRYPOINT eval $(ssh-agent) && ssh-add; /bin/bash -c ./wire/deploy.sh
