// Autogenerated by VisionMarkerTrained.CreateTestImage on 2014-10-08 13:21:47

const s32 numMarkers_groundTruth = 24;

const f32 corners_groundTruth[numMarkers_groundTruth][4][2] = {
	{{25.38f,27.67f},{25.38f,67.67f},{65.38f,27.67f},{65.38f,67.67f}}, // B
	{{71.10f,27.67f},{71.10f,67.67f},{111.10f,27.67f},{111.10f,67.67f}}, // 0
	{{116.81f,27.67f},{116.81f,67.67f},{156.81f,27.67f},{156.81f,67.67f}}, // DICE3
	{{162.52f,27.67f},{162.52f,67.67f},{202.52f,27.67f},{202.52f,67.67f}}, // DICE6
	{{208.24f,27.67f},{208.24f,67.67f},{248.24f,27.67f},{248.24f,67.67f}}, // BRIDGESUNRIGHT
	{{253.95f,27.67f},{253.95f,67.67f},{293.95f,27.67f},{293.95f,67.67f}}, // ANKILOGO
	{{25.38f,75.67f},{25.38f,115.67f},{65.38f,75.67f},{65.38f,115.67f}}, // 1
	{{71.10f,75.67f},{71.10f,115.67f},{111.10f,75.67f},{111.10f,115.67f}}, // M
	{{116.81f,75.67f},{116.81f,115.67f},{156.81f,75.67f},{156.81f,115.67f}}, // 4
	{{162.52f,75.67f},{162.52f,115.67f},{202.52f,75.67f},{202.52f,115.67f}}, // E
	{{208.24f,75.67f},{208.24f,115.67f},{248.24f,75.67f},{248.24f,115.67f}}, // BRIDGEMOONLEFT
	{{253.95f,75.67f},{253.95f,115.67f},{293.95f,75.67f},{293.95f,115.67f}}, // STAR5
	{{25.38f,123.67f},{25.38f,163.67f},{65.38f,123.67f},{65.38f,163.67f}}, // R
	{{71.10f,123.67f},{71.10f,163.67f},{111.10f,123.67f},{111.10f,163.67f}}, // N
	{{116.81f,123.67f},{116.81f,163.67f},{156.81f,123.67f},{156.81f,163.67f}}, // L
	{{162.52f,123.67f},{162.52f,163.67f},{202.52f,123.67f},{202.52f,163.67f}}, // 3
	{{208.24f,123.67f},{208.24f,163.67f},{248.24f,123.67f},{248.24f,163.67f}}, // FIRE
	{{253.95f,123.67f},{253.95f,163.67f},{293.95f,123.67f},{293.95f,163.67f}}, // RAMPBACK
	{{25.38f,171.67f},{25.38f,211.67f},{65.38f,171.67f},{65.38f,211.67f}}, // 2
	{{71.10f,171.67f},{71.10f,211.67f},{111.10f,171.67f},{111.10f,211.67f}}, // BRIDGEMOONRIGHT
	{{116.81f,171.67f},{116.81f,211.67f},{156.81f,171.67f},{156.81f,211.67f}}, // T
	{{162.52f,171.67f},{162.52f,211.67f},{202.52f,171.67f},{202.52f,211.67f}}, // RAMPFRONT
	{{208.24f,171.67f},{208.24f,211.67f},{248.24f,171.67f},{248.24f,211.67f}}, // PLATFORMEAST
	{{253.95f,171.67f},{253.95f,211.67f},{293.95f,171.67f},{293.95f,211.67f}}, // 8
};

const Anki::Vision::MarkerType markerTypes_groundTruth[numMarkers_groundTruth] = {
	Anki::Vision::MARKER_B,
	Anki::Vision::MARKER_0,
	Anki::Vision::MARKER_DICE3,
	Anki::Vision::MARKER_DICE6,
	Anki::Vision::MARKER_BRIDGESUNRIGHT,
	Anki::Vision::MARKER_ANKILOGO,
	Anki::Vision::MARKER_1,
	Anki::Vision::MARKER_M,
	Anki::Vision::MARKER_4,
	Anki::Vision::MARKER_E,
	Anki::Vision::MARKER_BRIDGEMOONLEFT,
	Anki::Vision::MARKER_STAR5,
	Anki::Vision::MARKER_R,
	Anki::Vision::MARKER_N,
	Anki::Vision::MARKER_L,
	Anki::Vision::MARKER_3,
	Anki::Vision::MARKER_FIRE,
	Anki::Vision::MARKER_RAMPBACK,
	Anki::Vision::MARKER_2,
	Anki::Vision::MARKER_BRIDGEMOONRIGHT,
	Anki::Vision::MARKER_T,
	Anki::Vision::MARKER_RAMPFRONT,
	Anki::Vision::MARKER_PLATFORMEAST,
	Anki::Vision::MARKER_8,
};

