// Autogenerated by VisionMarkerTrained.CreateTestImage on 2016-02-12 13:35:49

const s32 numMarkers_groundTruth = 24;

const f32 corners_groundTruth[numMarkers_groundTruth][4][2] = {
	{{25.38f,27.67f},{25.38f,67.67f},{65.38f,27.67f},{65.38f,67.67f}}, // LIGHTNINGBOLT_02
	{{71.10f,27.67f},{71.10f,67.67f},{111.10f,27.67f},{111.10f,67.67f}}, // LIGHTCUBEJ_SIDE2
	{{116.81f,27.67f},{116.81f,67.67f},{156.81f,27.67f},{156.81f,67.67f}}, // J
	{{162.52f,27.67f},{162.52f,67.67f},{202.52f,27.67f},{202.52f,67.67f}}, // LIGHTCUBEI_BOTTOM
	{{208.24f,27.67f},{208.24f,67.67f},{248.24f,27.67f},{248.24f,67.67f}}, // F
	{{253.95f,27.67f},{253.95f,67.67f},{293.95f,27.67f},{293.95f,67.67f}}, // A
	{{25.38f,75.67f},{25.38f,115.67f},{65.38f,75.67f},{65.38f,115.67f}}, // N
	{{71.10f,75.67f},{71.10f,115.67f},{111.10f,75.67f},{111.10f,115.67f}}, // E
	{{116.81f,75.67f},{116.81f,115.67f},{156.81f,75.67f},{156.81f,115.67f}}, // LIGHTCUBEK_SIDE2
	{{162.52f,75.67f},{162.52f,115.67f},{202.52f,75.67f},{202.52f,115.67f}}, // LIGHTCUBEK_SIDE4
	{{208.24f,75.67f},{208.24f,115.67f},{248.24f,75.67f},{248.24f,115.67f}}, // 5
	{{253.95f,75.67f},{253.95f,115.67f},{293.95f,75.67f},{293.95f,115.67f}}, // 4
	{{25.38f,123.67f},{25.38f,163.67f},{65.38f,123.67f},{65.38f,163.67f}}, // LIGHTNINGBOLTHOLLOW_03
	{{71.10f,123.67f},{71.10f,163.67f},{111.10f,123.67f},{111.10f,163.67f}}, // LIGHTNINGBOLTHOLLOW_04
	{{116.81f,123.67f},{116.81f,163.67f},{156.81f,123.67f},{156.81f,163.67f}}, // R
	{{162.52f,123.67f},{162.52f,163.67f},{202.52f,123.67f},{202.52f,163.67f}}, // SQUAREPLUSCORNERS
	{{208.24f,123.67f},{208.24f,163.67f},{248.24f,123.67f},{248.24f,163.67f}}, // DICE2
	{{253.95f,123.67f},{253.95f,163.67f},{293.95f,123.67f},{293.95f,163.67f}}, // RAMPRIGHT
	{{25.38f,171.67f},{25.38f,211.67f},{65.38f,171.67f},{65.38f,211.67f}}, // BRIDGESUNLEFT
	{{71.10f,171.67f},{71.10f,211.67f},{111.10f,171.67f},{111.10f,211.67f}}, // BRIDGESUNRIGHT
	{{116.81f,171.67f},{116.81f,211.67f},{156.81f,171.67f},{156.81f,211.67f}}, // DICE6
	{{162.52f,171.67f},{162.52f,211.67f},{202.52f,171.67f},{202.52f,211.67f}}, // GOALFLAG
	{{208.24f,171.67f},{208.24f,211.67f},{248.24f,171.67f},{248.24f,211.67f}}, // BEE
	{{253.95f,171.67f},{253.95f,211.67f},{293.95f,171.67f},{293.95f,211.67f}}, // B
};

const Anki::Vision::MarkerType markerTypes_groundTruth[numMarkers_groundTruth] = {
	Anki::Vision::MARKER_LIGHTNINGBOLT_02,
	Anki::Vision::MARKER_LIGHTCUBEJ_SIDE2,
	Anki::Vision::MARKER_J,
	Anki::Vision::MARKER_LIGHTCUBEI_BOTTOM,
	Anki::Vision::MARKER_F,
	Anki::Vision::MARKER_A,
	Anki::Vision::MARKER_N,
	Anki::Vision::MARKER_E,
	Anki::Vision::MARKER_LIGHTCUBEK_SIDE2,
	Anki::Vision::MARKER_LIGHTCUBEK_SIDE4,
	Anki::Vision::MARKER_5,
	Anki::Vision::MARKER_4,
	Anki::Vision::MARKER_LIGHTNINGBOLTHOLLOW_03,
	Anki::Vision::MARKER_LIGHTNINGBOLTHOLLOW_04,
	Anki::Vision::MARKER_R,
	Anki::Vision::MARKER_SQUAREPLUSCORNERS,
	Anki::Vision::MARKER_DICE2,
	Anki::Vision::MARKER_RAMPRIGHT,
	Anki::Vision::MARKER_BRIDGESUNLEFT,
	Anki::Vision::MARKER_BRIDGESUNRIGHT,
	Anki::Vision::MARKER_DICE6,
	Anki::Vision::MARKER_GOALFLAG,
	Anki::Vision::MARKER_BEE,
	Anki::Vision::MARKER_B,
};

