#ifndef __HARDWARE_H
#define __HARDWARE_H

//#define EP1_HEADBOARD

#ifdef EP1_HEADBOARD
  #define CAMERA_DATA_GPIO GPIOC_PDIR
  GPIO_PIN_SOURCE(AUDIO_STANDBY, PTE, 25);

  GPIO_PIN_SOURCE(WS, PTD, 4);

  GPIO_PIN_SOURCE(CAM_D1, PTC, 1);
  GPIO_PIN_SOURCE(CAM_D2, PTC, 2);
  GPIO_PIN_SOURCE(CAM_D3, PTC, 3);
  GPIO_PIN_SOURCE(CAM_D4, PTC, 4);
  GPIO_PIN_SOURCE(CAM_D5, PTC, 5);
  GPIO_PIN_SOURCE(CAM_D6, PTC, 6);
  GPIO_PIN_SOURCE(CAM_D7, PTC, 7);
  
  GPIO_PIN_SOURCE(CAM_HSYNC,   PTD, 5);
  GPIO_PIN_SOURCE(CAM_XCLK,    PTB, 0);
  
  GPIO_PIN_SOURCE(CAM_RESET_N, PTA, 1);
  GPIO_PIN_SOURCE(CAM_PWDN,    PTA, 4);

  GPIO_PIN_SOURCE(POWEREN,    PTA, 2);
  GPIO_PIN_SOURCE(SCK,        PTE, 17);
  GPIO_PIN_SOURCE(MOSI,       PTE, 18);

  GPIO_PIN_SOURCE(OLED_RST, PTA,  19);
#else
  #define CAMERA_DATA_GPIO GPIOC_PDIR

  GPIO_PIN_SOURCE(WS, PTD, 4);

// For headboard 4.1 - there is no D0
  GPIO_PIN_SOURCE(CAM_D1, PTC, 1);
  GPIO_PIN_SOURCE(CAM_D2, PTC, 2);
  GPIO_PIN_SOURCE(CAM_D3, PTC, 3);
  GPIO_PIN_SOURCE(CAM_D4, PTC, 4);
  GPIO_PIN_SOURCE(CAM_D5, PTC, 5);
  GPIO_PIN_SOURCE(CAM_D6, PTC, 6);
  GPIO_PIN_SOURCE(CAM_D7, PTC, 7);
  
  GPIO_PIN_SOURCE(CAM_HSYNC,   PTD, 5);
  GPIO_PIN_SOURCE(CAM_XCLK,    PTB, 0);
  
  GPIO_PIN_SOURCE(CAM_RESET_N, PTE, 25);
  GPIO_PIN_SOURCE(CAM_PWDN,   PTA, 1);

  GPIO_PIN_SOURCE(POWEREN,    PTA, 2);
  GPIO_PIN_SOURCE(SCK,        PTE, 17);
  GPIO_PIN_SOURCE(MOSI,       PTE, 18);

  GPIO_PIN_SOURCE(OLED_RST, PTA,  19);
#endif

#endif
