scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/cutils/properties.h inc/cutils/
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/linux/msm_ion.h inc/linux
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/linux/staging/android/uapi/msm_ion.h  inc/linux/staging/android/
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/linux/staging/android/uapi/ion.h inc/linux/staging/android/uapi/
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h inc/linux
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/mm_camera_interface.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/media/msmb_camera.h inc/media
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/cam_intf.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/out/target/product/msm8909/obj/KERNEL_OBJ/usr/include/media/msmb_isp.h inc/media
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/cam_types.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/cam_queue.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/cam_list.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/common/mm_jpeg_interface.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/mm-camera-test/../../../mm-image-codec/qomx_core/QOMX_JpegExtensions.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/frameworks/native/include/media/openmax/OMX_Image.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/frameworks/native/include/media/openmax/OMX_IVCommon.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/frameworks/native/include/media/openmax/OMX_Core.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/frameworks/native/include/media/openmax/OMX_Index.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/frameworks/native/include/media/openmax/OMX_Types.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/hardware/qcom/camera/QCamera2/stack/mm-camera-test/../../../mm-image-codec/qexif/qexif.h inc
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/utils/Log.h inc/utils
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/utils/log.h inc/utils
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/cutils/log.h inc/cutils
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/log/log.h inc/log
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/log/logd.h inc/log
scp andbuild@10.10.7.39:/mnt/devel/la2.0.2/kernel/system/core/include/log/uio.h inc/log
