#include "BlockDefinitionMacros.h"

//START_BLOCK_DEFINITION(FUEL, (44.f,44.f,44.f), (0xff,0x0,0x0))
//ADD_ALL_FACES(26.f, Vision::MARKER_BATTERIES)
//END_BLOCK_DEFINITION

#define DEFAULT_BLOCK_MARKER_SIZE 25.f

START_BLOCK_DEFINITION(BULLSEYE2, (44.f,44.f,44.f), (0x0,0xff,0x0))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FIRE, (44.f,44.f,44.f), (0x0,0x0,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_FIRE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SQTARGET, (44.f,44.f,44.f), (0x0,0xff,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SQUAREPLUSCORNERS)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ANGRYFACE, (44.f,44.f,44.f), (0x0,0xff,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANGRYFACE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(STAR5, (44.f,44.f,44.f), (0xff,0xff,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_STAR5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(DICE, (16.f,16.f,16.f), (0xff,0x00,0x00))
ADD_FACE_CODE(FRONT_FACE,  12.f, Vision::MARKER_DICE1)
ADD_FACE_CODE(BACK_FACE,   12.f, Vision::MARKER_DICE2)
ADD_FACE_CODE(LEFT_FACE,   12.f, Vision::MARKER_DICE3)
ADD_FACE_CODE(RIGHT_FACE,  12.f, Vision::MARKER_DICE4)
ADD_FACE_CODE(TOP_FACE,    12.f, Vision::MARKER_DICE5)
ADD_FACE_CODE(BOTTOM_FACE, 12.f, Vision::MARKER_DICE6)
END_BLOCK_DEFINITION

// Remove this one if it is also used on the mat!
START_BLOCK_DEFINITION(ANKILOGO, (44.f,44.f,44.f), (0xff,0xff,0x0))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANKILOGO)
END_BLOCK_DEFINITION

// Number blocks
START_BLOCK_DEFINITION(NUMBER1, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_1)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER2, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER3, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_3)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER4, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_4)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER5, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER6, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_6)
END_BLOCK_DEFINITION

//Exclamation point
START_BLOCK_DEFINITION(BANGBANGBANG, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG)
END_BLOCK_DEFINITION

// Question mark
START_BLOCK_DEFINITION(QUESTION, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_QUESTIONMARK)
END_BLOCK_DEFINITION

#undef DEFAULT_BLOCK_MARKER_SIZE
