#include "BlockDefinitionMacros.h"

#if 0 // EXAMPLE
// Foo message
START_BLOCK_DEFINITION(Foo, 1)
ADD_MESSAGE_MEMBER(f32, fooMember1)
ADD_MESSAGE_MEMBER(u16, fooMember2)
ADD_MESSAGE_MEMBER(u8,  fooMember3)
END_MESSAGE_DEFINITION(Foo)
#endif 

//START_BLOCK_DEFINITION(FUEL, (44.f,44.f,44.f), (0xff,0x0,0x0))
//ADD_ALL_FACES(26.f, Vision::MARKER_BATTERIES)
//END_BLOCK_DEFINITION

#define DEFAULT_BLOCK_MARKER_SIZE 25.f

START_BLOCK_DEFINITION(BULLSEYE2, (44.f,44.f,44.f), (0x0,0xff,0x0))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FIRE, (44.f,44.f,44.f), (0x0,0x0,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_FIRE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SQTARGET, (44.f,44.f,44.f), (0x0,0xff,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SQUAREPLUSCORNERS)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ANGRYFACE, (44.f,44.f,44.f), (0x0,0xff,0xff))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANGRYFACE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(STAR5, (44.f,44.f,44.f), (0xff,0xff,0x00))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_STAR5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(DICE, (44.f,44.f,44.f), (0xff,0x00,0x00))
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE1)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE2)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE3)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE4)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE5)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_DICE6)
END_BLOCK_DEFINITION

// Remove this one if it is also used on the mat!
START_BLOCK_DEFINITION(ANKILOGO, (44.f,44.f,44.f), (0xff,0xff,0x0))
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANKILOGO)
END_BLOCK_DEFINITION

#undef DEFAULT_BLOCK_MARKER_SIZE

/*
START_BLOCK_DEFINITION(TEMP2x1, (120.f, 60.f, 60.f), (0.f,0.f,1.f))
//SET_COLOR(0.f, 0.f, 1.f) // Blue
//SET_SIZE(120.f, 60.f, 60.f)
ADD_FACE_CODE(FRONT_FACE, 32.f,
              115, 117, 167, 238, 206, 221, 156, 168,  58, 114, 118)
ADD_FACE_CODE(LEFT_FACE, 32.f,
              115, 117, 167, 238, 206, 221, 156, 168,  58, 114, 118)
END_BLOCK_DEFINITION
*/