#!/system/bin/sh

#unlock the read-only partition (until next boot)
#adb remount

#https://stackoverflow.com/questions/13089694/adb-remount-permission-denied-but-able-to-access-super-user-in-shell-android#13366444
#"Both adb remount and adb root don't work on a production build without altering ro.secure, but you can still
# remount /system by opening a shell, asking for root permissions and typing the mount command."

#modified init sequence after os update
#cd /data
echo 'cd /data/local/fixture && ./helper' > /data/appinit.sh
exit

#start helper application after normal boot
if ! grep -q './helper' "/system/etc/userinit.sh"; then #if we haven't already added...
  echo remount read-only partition
  cd /
  mount -o rw,remount /system
  
  echo adding helper to bootup
  cd /system/etc
  echo 'cd /data/local/fixture && ./helper' > userinit_helper.sh
  cat userinit_helper.sh >> userinit.sh
  rm userinit_helper.sh
  
else
  echo helper boot ok
fi
