#!/system/bin/sh

#unlock the read-only partition (until next boot)
#adb remount

#https://stackoverflow.com/questions/13089694/adb-remount-permission-denied-but-able-to-access-super-user-in-shell-android#13366444
#"Both adb remount and adb root don't work on a production build without altering ro.secure, but you can still
# remount /system by opening a shell, asking for root permissions and typing the mount command."

cd /
mount -o rw,remount /system

#start helper application after normal boot
#XXX: check if already done? Prevent adding multiple identical calls
cd /system/etc
echo 'cd /data/local/fixture && ./helper' > userinit_helper.sh
cat userinit_helper.sh >> userinit.sh
rm userinit_helper.sh
