android_library(
  name = 'lib',
  srcs = glob(['*.java']),
  deps = [
    '//:cozmojava_lib',
    '//standalone-apk/resources:res',
    '//:native_libs_for_standalone',
  ],
  visibility = [
    '//:cozmoengine_standalone_app',
  ],
)

project_config(
  src_target = ':lib',
)
