// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/advertisementTypes.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/advertisementTypes.clad

#include "clad/types/advertisementTypes.h"

namespace Anki {

namespace Cozmo {

bool AdvertisementRegistrationMsg::IsValid() const
{
    return (true);
}

uint32_t AdvertisementRegistrationMsg::Size() const
{
  uint32_t result = 0;
  // toEnginePort
  result += 2; // uint_16
  // fromEnginePort
  result += 2; // uint_16
  // id
  result += 1; // uint_8
  // enableAdvertisement
  result += 1; // bool
  // oneShot
  result += 1; // bool
  // ip
  result += 1; // uint_8 (ip_length)
  result += 1 * this->ip_length; // uint_8
  return result;
}

bool AdvertisementMsg::IsValid() const
{
    return (true);
}

uint32_t AdvertisementMsg::Size() const
{
  uint32_t result = 0;
  // toEnginePort
  result += 2; // uint_16
  // fromEnginePort
  result += 2; // uint_16
  // id
  result += 1; // uint_8
  // ip
  result += 1; // uint_8 (ip_length)
  result += 1 * this->ip_length; // uint_8
  return result;
}

} // namespace Cozmo

} // namespace Anki

