// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/animationEvents.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/animationEvents.clad

#include "clad/types/animationEvents.h"

namespace Anki {

namespace Cozmo {

#ifdef CLAD_DEBUG
const char* AnimEventToString(AnimEvent m)
{
  switch(m) {
    case TAPPED_BLOCK:
      return "TAPPED_BLOCK";
    case DEVICE_AUDIO_TRIGGER:
      return "DEVICE_AUDIO_TRIGGER";
    case Count:
      return "Count";
    default:
      return 0;
  }
}
#endif // CLAD_DEBUG

} // namespace Cozmo

} // namespace Anki

