// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/cameraFOVInfo.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/cameraFOVInfo.clad

#ifndef __CLAD_TYPES_CAMERA_FOV_INFO_H__
#define __CLAD_TYPES_CAMERA_FOV_INFO_H__

#include <stdbool.h>
#include <stdint.h>

namespace Anki {

namespace Cozmo {

// MESSAGE CameraFOVInfo
struct CameraFOVInfo
{
  float horizontalFOV;
  float verticalFOV;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 8;
  static const uint32_t MIN_SIZE = 8;
  inline uint32_t Size() const { return 8; }
  
};

} // namespace Cozmo

} // namespace Anki

#endif // __CLAD_TYPES_CAMERA_FOV_INFO_H__
