// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/controllerChannels.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/controllerChannels.clad

#include "clad/types/controllerChannels.h"

namespace Anki {

namespace Cozmo {

#ifdef CLAD_DEBUG
const char* ControllerChannelToString(ControllerChannel m)
{
  switch(m) {
    case controller_wheel:
      return "controller_wheel";
    case controller_head:
      return "controller_head";
    case controller_lift:
      return "controller_lift";
    case controller_steering:
      return "controller_steering";
    case controller_pointTurn:
      return "controller_pointTurn";
    default:
      return 0;
  }
}
#endif // CLAD_DEBUG

} // namespace Cozmo

} // namespace Anki

