// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/factoryFWOnly.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/factoryFWOnly.clad

#include "clad/types/factoryFWOnly.h"

namespace Anki {

namespace Cozmo {

namespace RobotInterface {

} // namespace RobotInterface

} // namespace Cozmo

} // namespace Anki

