// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/fwTestMessages.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/fwTestMessages.clad

#include "clad/types/fwTestMessages.h"

namespace Anki {

namespace Cozmo {

namespace RobotInterface {

#ifdef CLAD_DEBUG
const char* FactoryTestModeToString(FactoryTestMode m)
{
  switch(m) {
    case FTM_entry:
      return "FTM_entry";
    case FTM_None:
      return "FTM_None";
    case FTM_WiFiInfo:
      return "FTM_WiFiInfo";
    case FTM_StateMenu:
      return "FTM_StateMenu";
    case FTM_ADCInfo:
      return "FTM_ADCInfo";
    case FTM_ImuInfo:
      return "FTM_ImuInfo";
    case FTM_EncoderInfo:
      return "FTM_EncoderInfo";
    case FTM_motorLifeTest:
      return "FTM_motorLifeTest";
    case FTM_PlayPenTest:
      return "FTM_PlayPenTest";
    case FTM_SSID:
      return "FTM_SSID";
    case FTM_menus:
      return "FTM_menus";
    case FTM_cubeTest:
      return "FTM_cubeTest";
    case FTM_BLE_Menu:
      return "FTM_BLE_Menu";
    case FTM_BLE_On:
      return "FTM_BLE_On";
    case FTM_BLE_Off:
      return "FTM_BLE_Off";
    case FTM_WaitNV:
      return "FTM_WaitNV";
    case FTM_Sleepy:
      return "FTM_Sleepy";
    case FTM_FAC:
      return "FTM_FAC";
    case FTM_Off:
      return "FTM_Off";
    case FTM_IMUCalibration:
      return "FTM_IMUCalibration";
    default:
      return 0;
  }
}
#endif // CLAD_DEBUG

} // namespace RobotInterface

} // namespace Cozmo

} // namespace Anki

