// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/motorTypes.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/motorTypes.clad

#include "clad/types/motorTypes.h"

namespace Anki {

namespace Cozmo {

#ifdef CLAD_DEBUG
const char* MotorIDToString(MotorID m)
{
  switch(m) {
    case MOTOR_LEFT_WHEEL:
      return "MOTOR_LEFT_WHEEL";
    case MOTOR_RIGHT_WHEEL:
      return "MOTOR_RIGHT_WHEEL";
    case MOTOR_LIFT:
      return "MOTOR_LIFT";
    case MOTOR_HEAD:
      return "MOTOR_HEAD";
    case MOTOR_COUNT:
      return "MOTOR_COUNT";
    default:
      return 0;
  }
}
#endif // CLAD_DEBUG

} // namespace Cozmo

} // namespace Anki

