// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/types/nvStorageTypes.clad
// Full command line: ../../tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 -C ./src/ -I -o ../generated/clad//robot/ clad/types/nvStorageTypes.clad

#ifndef __CLAD_TYPES_NV_STORAGE_TYPES_H__
#define __CLAD_TYPES_NV_STORAGE_TYPES_H__

#include <stdbool.h>
#include <stdint.h>

namespace Anki {

namespace Cozmo {

namespace NVStorage {

// ENUM NVEntryTag
enum {
  NVEntry_Invalid             = 0xffffffff, // 4294967295
  NVEntry_WipeAll             = 0xfffe0000, // 4294836224
  NVEntry_GameSkillLevels     = 2,          // 2
  NVEntry_Junk                = 0xffff,     // 65535
  NVEntry_FaceAlbumData       = 0xfa0000,   // 16384000
  NVEntry_FaceEnrollData      = 0xfe0000,   // 16646144
  NVEntry_MultiBlobJunk       = 0x7fff0000, // 2147418112
  NVEntry_BirthCertificate    = 0x80000000, // 2147483648
  NVEntry_CameraCalib         = 0x80000001, // 2147483649
  NVEntry_ToolCodeInfo        = 0x80000002, // 2147483650
  NVEntry_CalibPose           = 0x80000003, // 2147483651
  NVEntry_CalibMetaInfo       = 0x80000004, // 2147483652
  NVEntry_ObservedCubePose    = 0x80000005, // 2147483653
  NVEntry_IMUInfo             = 0x80000006, // 2147483654
  NVEntry_CliffValOnDrop      = 0x80000007, // 2147483655
  NVEntry_CliffValOnGround    = 0x80000008, // 2147483656
  NVEntry_PlaypenTestResults  = 0x80000010, // 2147483664
  NVEntry_FactoryLock         = 0x80000011, // 2147483665
  NVEntry_CalibImage1         = 0x80010000, // 2147549184
  NVEntry_CalibImage2         = 0x80020000, // 2147614720
  NVEntry_CalibImage3         = 0x80030000, // 2147680256
  NVEntry_CalibImage4         = 0x80040000, // 2147745792
  NVEntry_CalibImage5         = 0x80050000, // 2147811328
  NVEntry_CalibImage6         = 0x80060000, // 2147876864
  NVEntry_ToolCodeImageLeft   = 0x80100000, // 2148532224
  NVEntry_ToolCodeImageRight  = 0x80110000, // 2148597760
  NVEntry_PrePlaypenResults   = 0xc0000000, // 3221225472
  NVEntry_PrePlaypenCentroids = 0xc0000001, // 3221225473
  NVEntry_IMUAverages         = 0xc0000004, // 3221225476
};
typedef uint32_t NVEntryTag;

#ifdef CLAD_DEBUG
const char* NVEntryTagToString(NVEntryTag m);
#endif // CLAD_DEBUG

// ENUM NVResult
enum {
  NV_OKAY      = 0,  // 0
  NV_SCHEDULED = 1,  // 1
  NV_NO_DO     = 2,  // 2
  NV_NOT_FOUND = -1, // -1
  NV_NO_ROOM   = -2, // -2
  NV_ERROR     = -3, // -3
  NV_TIMEOUT   = -4, // -4
  NV_BUSY      = -5, // -5
  NV_BAD_ARGS  = -6, // -6
  NV_NO_MEM    = -7, // -7
};
typedef int8_t NVResult;

#ifdef CLAD_DEBUG
const char* NVResultToString(NVResult m);
#endif // CLAD_DEBUG

// ENUM NVOperation
enum {
  NVOP_READ     = 0, // 0
  NVOP_WRITE,        // 1
  NVOP_ERASE,        // 2
  NVOP_WIPEALL,      // 3
};
typedef uint8_t NVOperation;

#ifdef CLAD_DEBUG
const char* NVOperationToString(NVOperation m);
#endif // CLAD_DEBUG

} // namespace NVStorage

} // namespace Cozmo

} // namespace Anki

#endif // __CLAD_TYPES_NV_STORAGE_TYPES_H__
