# Compile by typing "python setup.py install"
# Requires python, with the numpy and cython packages installed

from distutils.core import setup
from Cython.Build import cythonize
from distutils.extension import Extension

import numpy

extensions = [
    Extension("anki",
        ["anki.pyx",
        "anki_interface.cpp",
        "../../coretech/common/robot/src/array2d.cpp",
        "../../coretech/common/robot/src/benchmarking.cpp",
        "../../coretech/common/robot/src/comparisons.cpp",
        "../../coretech/common/robot/src/compress.cpp",
        "../../coretech/common/robot/src/decisionTree.cpp",
        "../../coretech/common/robot/src/draw.cpp",
        "../../coretech/common/robot/src/errorHandling.cpp",
        "../../coretech/common/robot/src/find.cpp",
        "../../coretech/common/robot/src/fixedLengthList.cpp",
        "../../coretech/common/robot/src/flags.cpp",
        "../../coretech/common/robot/src/geometry.cpp",
        "../../coretech/common/robot/src/hostIntrinsics_m4.cpp",
        "../../coretech/common/robot/src/interpolate.cpp",
        "../../coretech/common/robot/src/matrix.cpp",
        "../../coretech/common/robot/src/memory.cpp",
        "../../coretech/common/robot/src/opencvLight.cpp",
        "../../coretech/common/robot/src/sequences.cpp",
        "../../coretech/common/robot/src/serialize.cpp",
        "../../coretech/common/robot/src/trig_fast.cpp",
        "../../coretech/common/robot/src/utilities.cpp",
        "../../coretech/common/robot/src/utilities_c.c",
        "../../coretech/common/shared/src/utilities_shared.cpp",
        "../../coretech/vision/robot/src/binaryTracker.cpp",
        "../../coretech/vision/robot/src/cameraImagingPipeline.cpp",
        "../../coretech/vision/robot/src/cascadeClassifier.cpp",
        "../../coretech/vision/robot/src/colorConversion.cpp",
        "../../coretech/vision/robot/src/computeCharacteristicScale.cpp",
        "../../coretech/vision/robot/src/computeCharacteristicScale_binomial.cpp",
        "../../coretech/vision/robot/src/computeQuadrilaterals.cpp",
        "../../coretech/vision/robot/src/connectedComponents.cpp",
        "../../coretech/vision/robot/src/decisionTree_vision.cpp",
        "../../coretech/vision/robot/src/detectFiducialMarkers.cpp",
        "../../coretech/vision/robot/src/distanceTransform.cpp",
        "../../coretech/vision/robot/src/draw_vision.cpp",
        "../../coretech/vision/robot/src/edgeDetection.cpp",
        "../../coretech/vision/robot/src/features.cpp",
        "../../coretech/vision/robot/src/fiducialMarkers.cpp",
        "../../coretech/vision/robot/src/filtering.cpp",
        "../../coretech/vision/robot/src/histogram.cpp",
        "../../coretech/vision/robot/src/integralImage.cpp",
        "../../coretech/vision/robot/src/laplacianPeaks.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Affine.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Fast.cpp",
        "../../coretech/vision/robot/src/lucasKanade_General.cpp",
        "../../coretech/vision/robot/src/lucasKanade_KLT.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Projective.cpp",
        "../../coretech/vision/robot/src/lucasKanade_SampledPlanar6dof.cpp",
        "../../coretech/vision/robot/src/lucasKanade_SampledProjective.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Slow.cpp",
        "../../coretech/vision/robot/src/opencvLight_vision.cpp",
        "../../coretech/vision/robot/src/perspectivePoseEstimation.cpp",
        "../../coretech/vision/robot/src/quadRefinement.cpp",
        "../../coretech/vision/robot/src/recognizeFaces.cpp",
        "../../coretech/vision/robot/src/traceBoundary.cpp",
        "../../coretech/vision/robot/src/transformations.cpp",
        "../../coretech/vision/robot/src/upsample.cpp"
         ],
        include_dirs = ["../../include",
                        "../../coretech/common/include",
                        "../../coretech/vision/include",
                        "../../coretech/vision/robot/src/",
                        numpy.get_include()],
        libraries = ["z"],
        extra_compile_args = ["-DANKICORETECH_EMBEDDED_USE_MALLOC",
                              "-DANKICORETECH_EMBEDDED_USE_ZLIB"]),
]

setup(
  name = "anki",
  ext_modules = cythonize(extensions),
)