# Compile by typing "python setup.py install"
# Requires python, with the numpy and cython packages installed

from distutils.core import setup
from Cython.Build import cythonize
from distutils.extension import Extension

import numpy

extensions = [
    Extension("ankic",
        ["ankic.pyx",
        "ankic_interface.cpp",
        "../../coretech/common/robot/src/array2d.cpp",
        "../../coretech/common/robot/src/benchmarking.cpp",
        "../../coretech/common/robot/src/comparisons.cpp",
        "../../coretech/common/robot/src/compress.cpp",
        "../../coretech/common/robot/src/decisionTree.cpp",
        "../../coretech/common/robot/src/draw.cpp",
        "../../coretech/common/robot/src/errorHandling.cpp",
        "../../coretech/common/robot/src/find.cpp",
        "../../coretech/common/robot/src/fixedLengthList.cpp",
        "../../coretech/common/robot/src/flags.cpp",
        "../../coretech/common/robot/src/geometry.cpp",
        "../../coretech/common/robot/src/hostIntrinsics_m4.cpp",
        "../../coretech/common/robot/src/interpolate.cpp",
        "../../coretech/common/robot/src/matrix.cpp",
        "../../coretech/common/robot/src/memory.cpp",
        "../../coretech/common/robot/src/opencvLight.cpp",
        "../../coretech/common/robot/src/sequences.cpp",
        "../../coretech/common/robot/src/serialize.cpp",
        "../../coretech/common/robot/src/trig_fast.cpp",
        "../../coretech/common/robot/src/utilities.cpp",
        "../../coretech/common/robot/src/utilities_c.c",
        "../../coretech/common/shared/src/utilities_shared.cpp",
        "../../coretech/vision/robot/src/binaryTracker.cpp",
        "../../coretech/vision/robot/src/cameraImagingPipeline.cpp",
        "../../coretech/vision/robot/src/cascadeClassifier.cpp",
        "../../coretech/vision/robot/src/colorConversion.cpp",
        "../../coretech/vision/robot/src/computeCharacteristicScale.cpp",
        "../../coretech/vision/robot/src/computeCharacteristicScale_binomial.cpp",
        "../../coretech/vision/robot/src/computeQuadrilaterals.cpp",
        "../../coretech/vision/robot/src/connectedComponents.cpp",
        "../../coretech/vision/robot/src/decisionTree_vision.cpp",
        "../../coretech/vision/robot/src/detectFiducialMarkers.cpp",
        "../../coretech/vision/robot/src/distanceTransform.cpp",
        "../../coretech/vision/robot/src/draw_vision.cpp",
        "../../coretech/vision/robot/src/edgeDetection.cpp",
        "../../coretech/vision/robot/src/features.cpp",
        "../../coretech/vision/robot/src/fiducialMarkers.cpp",
        "../../coretech/vision/robot/src/filtering.cpp",
        "../../coretech/vision/robot/src/histogram.cpp",
        "../../coretech/vision/robot/src/integralImage.cpp",
        "../../coretech/vision/robot/src/laplacianPeaks.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Affine.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Fast.cpp",
        "../../coretech/vision/robot/src/lucasKanade_General.cpp",
        "../../coretech/vision/robot/src/lucasKanade_KLT.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Projective.cpp",
        "../../coretech/vision/robot/src/lucasKanade_SampledPlanar6dof.cpp",
        "../../coretech/vision/robot/src/lucasKanade_SampledProjective.cpp",
        "../../coretech/vision/robot/src/lucasKanade_Slow.cpp",
        "../../coretech/vision/robot/src/nearestNeighborLibrary.cpp",
        "../../coretech/vision/robot/src/opencvLight_vision.cpp",
        "../../coretech/vision/robot/src/perspectivePoseEstimation.cpp",
        "../../coretech/vision/robot/src/quadRefinement.cpp",
        "../../coretech/vision/robot/src/recognizeFaces.cpp",
        "../../coretech/vision/robot/src/traceBoundary.cpp",
        "../../coretech/vision/robot/src/transformations.cpp",
        "../../coretech/vision/robot/src/upsample.cpp"
         ],
        include_dirs = ["../../include",
                        "../../coretech/common/include",
                        "../../coretech/vision/include",
                        "../../coretech/vision/robot/src/",
                        "../../../coretech-external/opencv-2.4.8/modules/calib3d/include",
                        "../../../coretech-external/opencv-2.4.8/modules/contrib/include",
                        "../../../coretech-external/opencv-2.4.8/modules/core/include",
                        "../../../coretech-external/opencv-2.4.8/modules/features2d/include",
                        "../../../coretech-external/opencv-2.4.8/modules/flann/include",
                        "../../../coretech-external/opencv-2.4.8/modules/gpu/include",
                        "../../../coretech-external/opencv-2.4.8/modules/highgui/include",
                        "../../../coretech-external/opencv-2.4.8/modules/imgproc/include",
                        "../../../coretech-external/opencv-2.4.8/modules/legacy/include",
                        "../../../coretech-external/opencv-2.4.8/modules/ml/include",
                        "../../../coretech-external/opencv-2.4.8/modules/nonfree/include",
                        "../../../coretech-external/opencv-2.4.8/modules/objdetect/include",
                        "../../../coretech-external/opencv-2.4.8/modules/ocl/include",
                        "../../../coretech-external/opencv-2.4.8/modules/photo/include",
                        "../../../coretech-external/opencv-2.4.8/modules/stitching/include",
                        "../../../coretech-external/opencv-2.4.8/modules/superres/include",
                        "../../../coretech-external/opencv-2.4.8/modules/video/include",
                        "../../../coretech-external/opencv-2.4.8/modules/videostab/include",
                        numpy.get_include()],
        libraries = ["z", 
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_calib3d.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_contrib.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_core.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_features2d.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_flann.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_gpu.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_highgui.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_imgproc.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_legacy.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_ml.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_nonfree.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_objdetect.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_ocl.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_photo.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_stitching.2.4.8",
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_superres.2.4.8", 
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_video.2.4.8", 
                     "../../../coretech-external/build/opencv-2.4.8/lib/Debug/opencv_videostab.2.4.8"],
        extra_compile_args = ["-DANKICORETECH_EMBEDDED_USE_MALLOC",
                              "-DANKICORETECH_EMBEDDED_USE_ZLIB",
                              "-DANKICORETECH_EMBEDDED_USE_OPENCV"]),
]

setup(
  name = "ankic",
  ext_modules = cythonize(extensions),
)