#include "BlockDefinitionMacros.h"

//START_BLOCK_DEFINITION(FUEL, (44.f,44.f,44.f), (0xff,0x0,0x0))
//ADD_ALL_FACES(26.f, Vision::MARKER_BATTERIES)
//END_BLOCK_DEFINITION


#define DEFAULT_BLOCK_MARKER_SIZE 25.f

// Only 3 blocks for CREEP test
START_BLOCK_DEFINITION(KITTY, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_KITTY)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(BEE, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BEE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SPIDER, (44.f,44.f,44.f), RED)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SPIDER)
END_BLOCK_DEFINITION

// NOTE: Bullseye blocks have 23mm markers!
START_BLOCK_DEFINITION(BULLSEYE2, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(23.f, Vision::MARKER_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(BULLSEYE2_INVERTED, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(23.f, Vision::MARKER_INVERTED_BULLSEYE2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FIRE, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_FIRE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(SQTARGET, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_SQUAREPLUSCORNERS)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ANGRYFACE, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANGRYFACE)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(STAR5, (44.f,44.f,44.f), DARKGREEN)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_STAR5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(DICE, (16.f,16.f,16.f), OFFWHITE)
ADD_FACE_CODE(FRONT_FACE,  12.f, Vision::MARKER_DICE1, PreActionOrientation::NONE)
ADD_FACE_CODE(BACK_FACE,   12.f, Vision::MARKER_DICE2, PreActionOrientation::NONE)
ADD_FACE_CODE(LEFT_FACE,   12.f, Vision::MARKER_DICE3, PreActionOrientation::NONE)
ADD_FACE_CODE(RIGHT_FACE,  12.f, Vision::MARKER_DICE4, PreActionOrientation::NONE)
ADD_FACE_CODE(TOP_FACE,    12.f, Vision::MARKER_DICE5, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, 12.f, Vision::MARKER_DICE6, PreActionOrientation::NONE)
END_BLOCK_DEFINITION

// NOTE: Flag blocks have 23mm markers!
START_BLOCK_DEFINITION(FLAG, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_CHECKEREDFLAG)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FLAG2, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_CHECKEREDFLAG2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(FLAG_INVERTED, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(23.f, Vision::MARKER_INVERTED_CHECKEREDFLAG)
END_BLOCK_DEFINITION

// Remove this one if it is also used on the mat!
START_BLOCK_DEFINITION(ANKILOGO, (44.f,44.f,44.f), DEFAULT)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ANKILOGO)
END_BLOCK_DEFINITION

/*
// Number blocks
START_BLOCK_DEFINITION(NUMBER1, (44.f,44.f,44.f), DARKGRAY)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_1)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER2, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_2)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER3, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_3)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER4, (44.f,44.f,44.f), ORANGE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_4)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER5, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_5)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(NUMBER6, (44.f,44.f,44.f), BLUE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_6)
END_BLOCK_DEFINITION
*/

// Active Number Block #1 (w/ 6 different sides)
START_BLOCK_DEFINITION(LIGHTCUBE1, (44.f,44.f,44.f), ORANGE)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_01, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_02, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_03, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_04, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_05, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLT_06, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Active Number Block #2
START_BLOCK_DEFINITION(LIGHTCUBE2, (44.f,44.f,44.f), YELLOW)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_01, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_02, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_03, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_04, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_05, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTNINGBOLTHOLLOW_06, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Active Number Block #3
START_BLOCK_DEFINITION(LIGHTCUBE3, (44.f,44.f,44.f), RED)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_01, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_02, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_03, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_04, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_05, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLT_06, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Active Number Block #4
START_BLOCK_DEFINITION(LIGHTCUBE4, (44.f,44.f,44.f), BLUE)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_01, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_02, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_03, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_04, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_05, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_LIGHTNINGBOLTHOLLOW_06, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

/*
//Exclamation point
START_BLOCK_DEFINITION(BANGBANGBANG, (44.f,44.f,44.f), RED)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG)
END_BLOCK_DEFINITION
*/

// Exclamation mark - 2x1
START_BLOCK_DEFINITION(BANGBANGBANG, (88.f,44.f,44.f), GREEN)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_INVERTED_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_BANGBANGBANG, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

START_BLOCK_DEFINITION(ARROW, (44.f,44.f,44.f), YELLOW)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_ARROW)
END_BLOCK_DEFINITION


#undef DEFAULT_BLOCK_MARKER_SIZE
