// All message definitions should look like this:
//
//   START_MESSAGE_DEFINITION(MessageTypeName, Priority, DispatchFunctionPtr)
//   ADD_MESSAGE_MEMBER(MemberType, MemberName)
//   ADD_MESSAGE_MEMBER(MemberType, MemberName)
//   ...
//   END_MESSAGE_DEFINITION(MessageTypeName)
//
// For example:
//
//   START_MESSAGE_DEFINITION(CozmoMsg_Foo, 1, ProcessFoo)
//   ADD_MESSAGE_MEMBER(f32, fooMember1)
//   ADD_MESSAGE_MEMBER(u16, fooMember2)
//   ADD_MESSAGE_MEMBER(u8,  fooMember3)
//   END_MESSAGE_DEFINITION(CozmoMsg_Foo)
//
// To add a timestamp member, use the START_TIMESTAMPED_MESSAGE_DEFINITION
// command, which will add a member "timestamp" to the struct, with type
// "TimeStamp".
//
// IMPORTANT NOTE: You should always add members from largest to smallest type!
//                 (This prevents memory alignment badness when doing memcopies
//                  or casts later.)
//

// For now at least, Viz uses Robot-style message structures
#ifdef COZMO_BASESTATION
#define COZMO_BASESTATION_IS_DEFINED
#undef COZMO_BASESTATION
#endif

#ifndef COZMO_ROBOT
#define COZMO_ROBOT_IS_UNDEFINED
#define COZMO_ROBOT
#endif

#include "anki/cozmo/shared/MessageDefMacros_Robot.h"

// VizObject
START_MESSAGE_DEFINITION(VizObject, 1)
ADD_MESSAGE_MEMBER(u32, objectID)
ADD_MESSAGE_MEMBER(u32, objectTypeID)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(f32, x_size_m)
ADD_MESSAGE_MEMBER(f32, y_size_m)
ADD_MESSAGE_MEMBER(f32, z_size_m)
ADD_MESSAGE_MEMBER(f32, x_trans_m)
ADD_MESSAGE_MEMBER(f32, y_trans_m)
ADD_MESSAGE_MEMBER(f32, z_trans_m)
ADD_MESSAGE_MEMBER(f32, rot_deg)
ADD_MESSAGE_MEMBER(f32, rot_axis_x)
ADD_MESSAGE_MEMBER(f32, rot_axis_y)
ADD_MESSAGE_MEMBER(f32, rot_axis_z)
ADD_MESSAGE_MEMBER_ARRAY(f32, params, 4) // for object-specific parameters
END_MESSAGE_DEFINITION(VizObject)

// VizQuad
START_MESSAGE_DEFINITION(VizQuad, 1)
ADD_MESSAGE_MEMBER(u32, quadType)
ADD_MESSAGE_MEMBER(u32, quadID)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(f32, xUpperLeft)
ADD_MESSAGE_MEMBER(f32, yUpperLeft)
ADD_MESSAGE_MEMBER(f32, zUpperLeft)
ADD_MESSAGE_MEMBER(f32, xLowerLeft)
ADD_MESSAGE_MEMBER(f32, yLowerLeft)
ADD_MESSAGE_MEMBER(f32, zLowerLeft)
ADD_MESSAGE_MEMBER(f32, xUpperRight)
ADD_MESSAGE_MEMBER(f32, yUpperRight)
ADD_MESSAGE_MEMBER(f32, zUpperRight)
ADD_MESSAGE_MEMBER(f32, xLowerRight)
ADD_MESSAGE_MEMBER(f32, yLowerRight)
ADD_MESSAGE_MEMBER(f32, zLowerRight)
END_MESSAGE_DEFINITION(VizQuad)

// VizCameraQuad
START_MESSAGE_DEFINITION(VizCameraQuad, 1)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(f32, xUpperLeft)
ADD_MESSAGE_MEMBER(f32, yUpperLeft)
ADD_MESSAGE_MEMBER(f32, xLowerLeft)
ADD_MESSAGE_MEMBER(f32, yLowerLeft)
ADD_MESSAGE_MEMBER(f32, xUpperRight)
ADD_MESSAGE_MEMBER(f32, yUpperRight)
ADD_MESSAGE_MEMBER(f32, xLowerRight)
ADD_MESSAGE_MEMBER(f32, yLowerRight)
END_MESSAGE_DEFINITION(VizCameraQuad)

// VizCameraLine
START_MESSAGE_DEFINITION(VizCameraLine, 1)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(f32, xStart)
ADD_MESSAGE_MEMBER(f32, yStart)
ADD_MESSAGE_MEMBER(f32, xEnd)
ADD_MESSAGE_MEMBER(f32, yEnd)
END_MESSAGE_DEFINITION(VizCameraLine)

// VizCameraPoint
START_MESSAGE_DEFINITION(VizCameraOval, 1)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(f32, xCen)
ADD_MESSAGE_MEMBER(f32, yCen)
ADD_MESSAGE_MEMBER(f32, xRad)
ADD_MESSAGE_MEMBER(f32, yRad)
END_MESSAGE_DEFINITION(VizCameraOval)

// VizCameraText
START_MESSAGE_DEFINITION(VizCameraText, 1)
ADD_MESSAGE_MEMBER(u32, color)
ADD_MESSAGE_MEMBER(s32, x)
ADD_MESSAGE_MEMBER(s32, y)
ADD_MESSAGE_MEMBER_ARRAY(char, text, 32)
END_MESSAGE_DEFINITION(VizCameraText)

// EraseObject
START_MESSAGE_DEFINITION(VizEraseObject, 1)
ADD_MESSAGE_MEMBER(u32, objectID)
ADD_MESSAGE_MEMBER(u32, lower_bound_id)
ADD_MESSAGE_MEMBER(u32, upper_bound_id)
END_MESSAGE_DEFINITION(VizEraseObject)

// EraseQuad
START_MESSAGE_DEFINITION(VizEraseQuad, 1)
ADD_MESSAGE_MEMBER(u32, quadType)
ADD_MESSAGE_MEMBER(u32, quadID)
END_MESSAGE_DEFINITION(VizEraseQuad)

// VizSetRobot
START_MESSAGE_DEFINITION(VizSetRobot, 1)
ADD_MESSAGE_MEMBER(u32, robotID)
ADD_MESSAGE_MEMBER(f32, x_trans_m)
ADD_MESSAGE_MEMBER(f32, y_trans_m)
ADD_MESSAGE_MEMBER(f32, z_trans_m)
ADD_MESSAGE_MEMBER(f32, rot_rad)
ADD_MESSAGE_MEMBER(f32, rot_axis_x)
ADD_MESSAGE_MEMBER(f32, rot_axis_y)
ADD_MESSAGE_MEMBER(f32, rot_axis_z)
ADD_MESSAGE_MEMBER(f32, head_angle)
ADD_MESSAGE_MEMBER(f32, lift_angle)
END_MESSAGE_DEFINITION(VizSetRobot)


// VizAppendPathSegmentLine
START_MESSAGE_DEFINITION(VizAppendPathSegmentLine, 1)
ADD_MESSAGE_MEMBER(u32, pathID)
ADD_MESSAGE_MEMBER(f32, x_start_m)
ADD_MESSAGE_MEMBER(f32, y_start_m)
ADD_MESSAGE_MEMBER(f32, z_start_m)
ADD_MESSAGE_MEMBER(f32, x_end_m)
ADD_MESSAGE_MEMBER(f32, y_end_m)
ADD_MESSAGE_MEMBER(f32, z_end_m)
END_MESSAGE_DEFINITION(VizAppendPathSegmentLine)

// VizAppendPathSegmentArc
START_MESSAGE_DEFINITION(VizAppendPathSegmentArc, 1)
ADD_MESSAGE_MEMBER(u32, pathID)
ADD_MESSAGE_MEMBER(f32, x_center_m)
ADD_MESSAGE_MEMBER(f32, y_center_m)
ADD_MESSAGE_MEMBER(f32, radius_m)
ADD_MESSAGE_MEMBER(f32, start_rad)
ADD_MESSAGE_MEMBER(f32, sweep_rad)
END_MESSAGE_DEFINITION(VizAppendPathSegmentArc)

// VizSetPathColor
START_MESSAGE_DEFINITION(VizSetPathColor, 1)
ADD_MESSAGE_MEMBER(u32, pathID)
ADD_MESSAGE_MEMBER(u32, colorID)
END_MESSAGE_DEFINITION(VizSetPathColor)


// ErasePath
START_MESSAGE_DEFINITION(VizErasePath, 1)
ADD_MESSAGE_MEMBER(u32, pathID)
END_MESSAGE_DEFINITION(VizErasePath)


// VizDefineColor
START_MESSAGE_DEFINITION(VizDefineColor, 1)
ADD_MESSAGE_MEMBER(u32, colorID)
ADD_MESSAGE_MEMBER(f32, r)
ADD_MESSAGE_MEMBER(f32, g)
ADD_MESSAGE_MEMBER(f32, b)
ADD_MESSAGE_MEMBER(f32, alpha)
END_MESSAGE_DEFINITION(VizDefineColor)


// VizSetLabel
#define MAX_VIZ_LABEL_LENGTH 128
START_MESSAGE_DEFINITION(VizSetLabel, 1)
ADD_MESSAGE_MEMBER(u32, labelID)
ADD_MESSAGE_MEMBER(u32, colorID)
ADD_MESSAGE_MEMBER_ARRAY(u8, text, MAX_VIZ_LABEL_LENGTH)
END_MESSAGE_DEFINITION(VizSetLabel)


// VizDockingErrorSignal
START_MESSAGE_DEFINITION(VizDockingErrorSignal, 1)
ADD_MESSAGE_MEMBER(f32, x_dist)
ADD_MESSAGE_MEMBER(f32, y_dist)
ADD_MESSAGE_MEMBER(f32, angle)
END_MESSAGE_DEFINITION(VizDockingErrorSignal)


// VizImageChunk
#define MAX_VIZ_IMAGE_CHUNK_SIZE (1300)
START_MESSAGE_DEFINITION(VizImageChunk, 1)
ADD_MESSAGE_MEMBER(u32, chunkSize)
ADD_MESSAGE_MEMBER(u8, chunkId)
ADD_MESSAGE_MEMBER(u8, chunkCount)
ADD_MESSAGE_MEMBER(u8, imgId)
ADD_MESSAGE_MEMBER(u8, resolution)
ADD_MESSAGE_MEMBER(u8, encoding)  // See cozmoTypes.h
ADD_MESSAGE_MEMBER_ARRAY(u8, data, MAX_VIZ_IMAGE_CHUNK_SIZE)
END_MESSAGE_DEFINITION(VizImageChunk)

// VizVisionMarker
START_MESSAGE_DEFINITION(VizVisionMarker, 1)
ADD_MESSAGE_MEMBER(u16, topLeft_x)
ADD_MESSAGE_MEMBER(u16, topLeft_y)
ADD_MESSAGE_MEMBER(u16, topRight_x)
ADD_MESSAGE_MEMBER(u16, topRight_y)
ADD_MESSAGE_MEMBER(u16, bottomRight_x)
ADD_MESSAGE_MEMBER(u16, bottomRight_y)
ADD_MESSAGE_MEMBER(u16, bottomLeft_x)
ADD_MESSAGE_MEMBER(u16, bottomLeft_y)
ADD_MESSAGE_MEMBER(u8,  verified)
END_MESSAGE_DEFINITION(VizVisionMarker)

// VizShowObjects
START_MESSAGE_DEFINITION(VizShowObjects, 1)
ADD_MESSAGE_MEMBER(u8, show)
END_MESSAGE_DEFINITION(VizShowObjects)

// The maximum size of a VizMsg
#define MAX_VIZ_MSG_SIZE (2*MAX_VIZ_IMAGE_CHUNK_SIZE)

// VizTrackerQuad
START_MESSAGE_DEFINITION(VizTrackerQuad, 1)
ADD_MESSAGE_MEMBER(u16, topLeft_x)
ADD_MESSAGE_MEMBER(u16, topLeft_y)
ADD_MESSAGE_MEMBER(u16, topRight_x)
ADD_MESSAGE_MEMBER(u16, topRight_y)
ADD_MESSAGE_MEMBER(u16, bottomRight_x)
ADD_MESSAGE_MEMBER(u16, bottomRight_y)
ADD_MESSAGE_MEMBER(u16, bottomLeft_x)
ADD_MESSAGE_MEMBER(u16, bottomLeft_y)
END_MESSAGE_DEFINITION(VizTrackerQuad)

START_MESSAGE_DEFINITION(VizRobotState, 1)
// Copied from RobotState message
ADD_MESSAGE_MEMBER(u32, pose_frame_id)
ADD_MESSAGE_MEMBER(f32, pose_x)
ADD_MESSAGE_MEMBER(f32, pose_y)
ADD_MESSAGE_MEMBER(f32, pose_z)
ADD_MESSAGE_MEMBER(f32, pose_angle)
ADD_MESSAGE_MEMBER(f32, pose_pitch_angle)
ADD_MESSAGE_MEMBER(f32, lwheel_speed_mmps)
ADD_MESSAGE_MEMBER(f32, rwheel_speed_mmps)
ADD_MESSAGE_MEMBER(f32, headAngle)
ADD_MESSAGE_MEMBER(f32, liftHeight)
ADD_MESSAGE_MEMBER(u32, status)  // See RobotStatusFlag
ADD_MESSAGE_MEMBER(s32, numAnimBytesFree)
ADD_MESSAGE_MEMBER(u16, lastPathID)
ADD_MESSAGE_MEMBER(u8, proxLeft)
ADD_MESSAGE_MEMBER(u8, proxForward)
ADD_MESSAGE_MEMBER(u8, proxRight)
ADD_MESSAGE_MEMBER(u8, battVolt10x)
ADD_MESSAGE_MEMBER(u8, videoFramerateHZ)
ADD_MESSAGE_MEMBER(u8, animTag)
END_MESSAGE_DEFINITION(VizRobotState)


#ifdef COZMO_BASESTATION_IS_DEFINED
#define COZMO_BASESTATION
#undef COZMO_BASESTATION_IS_DEFINED
#endif

#ifdef COZMO_ROBOT_IS_UNDEFINED
#undef COZMO_ROBOT_IS_UNDEFINED
#undef COZMO_ROBOT
#endif

