"""
This file generated a c++ file, by automatically "instantiating templates"
To add some lines to this file, find replace (without the quotes) "\r\n" into "\\n' +\\\r\n            '"
"""

import sys
sys.path.insert(0, '../../coretech-common/python')
import generateFixedLengthList_cpp

def __GenerateTopOfFile():
    topString = \
        '/*\n\n\n\n\n\n\n\n\n\nThis file was automatically generated by the python script generateFixedLengthList_vision_cpp.py. Rather than editing this file, edit that script, then run "python generateFixedLengthList_vision_cpp.py".\n\n\n\n\n\n\n\n\n\n*/\n\n';

    topString += \
        '#include "anki/embeddedVision.h"\n' +\
        '\n' +\
        'namespace Anki\n' +\
        '{\n' +\
        '  namespace Embedded\n' +\
        '  {\n'

    return topString

def __GenerateBottomOfFile():
    bottomString = \
        '  } // namespace Embedded\n' +\
        '} // namespace Anki'

    return bottomString

def GenerateAndWriteFile(filename = '../src/embedded/fixedLengthList_vision.cpp'):
    topString = __GenerateTopOfFile()

    methodsDefinitions = generateFixedLengthList_cpp.__GenerateDefinitions(['ConnectedComponentSegment', 'FiducialMarker'], False)

    bottomString = __GenerateBottomOfFile()

    f = open(filename, 'w')
    f.write(topString)
    f.write(methodsDefinitions)
    f.write(bottomString)

    f.close()

if __name__ == "__main__":
    GenerateAndWriteFile()