#ifndef __REC_PROTOCOL_H
#define __REC_PROTOCOL_H

#include <stdint.h>

static const uint32_t RECOVER_SOURCE_HEAD = 0x64487852;
static const uint32_t RECOVER_SOURCE_BODY = 0x64427852;
static const int TRANSMIT_BLOCK_SIZE = 0x1000;

enum RECOVERY_COMMAND {
  COMMAND_DONE  = 0x00,
  COMMAND_FLASH = 0x01
};

enum RECOVERY_STATE {
  STATE_IDLE,
  STATE_NACK,
  STATE_RUNNING,
  STATE_BUSY,
  STATE_SYNC,
  STATE_UNKNOWN
};

#endif
