#!/bin/sh
esn="$1"
echo esn=$esn

killall -9 adbd

mode=$(cat /sys/kernel/debug/msm_otg/mode)
if [ "$mode" != "host" ]; then
  echo none > /sys/kernel/debug/msm_otg/mode
  echo host > /sys/kernel/debug/msm_otg/mode
fi

insmod ./usbserial.ko vendor=0x05c6 product=0x9008
sleep 1
lsusb
#./emmcdl/emmcdl -p 0 -info
./emmcdl/emmcdl -p 0 -f emmcdl/prog_emmc_firehose_8909_ddr.mbn -x emmcdl/anki.xml -SetActivePartition 0
