#ifndef DEBUG_H_
#define DEBUG_H_

#define DEBUG_MAIN_EXECUTION 0
#define DEBUG_WHEEL_CONTROLLER 0
#define DEBUG_STEERING_CONTROLLER 0
#define DEBUG_SPEED_CONTROLLER 0
#define DEBUG_PATH_FOLLOWER 0
#define DEBUG_PATH 0
#define DEBUG_LOCALIZATION 0
#define DEBUG_LIFT_CONTROLLER 0
#define DEBUG_HEAD_CONTROLLER 0
#define DEBUG_DOCK_CONTROLLER 0


#define DEBUG_ANY (DEBUG_MAIN_EXECUTION \
                || DEBUG_WHEEL_CONTROLLER \
                || DEBUG_STEERING_CONTROLLER \
                || DEBUG_SPEED_CONTROLLER \
                || DEBUG_PATH_FOLLOWER \
                || DEBUG_LOCALIZATION \
                || DEBUG_LIFT_CONTROLLER \
                || DEBUG_HEAD_CONTROLLER \
                || DEBUG_DOCK_CONTROLLER)


#define FREE_DRIVE_DUBINS_TEST 0
#define ENABLE_KEYBOARD_CONTROL 0

#endif
