#ifndef DEBUG_H_
#define DEBUG_H_

#define DEBUG_MAIN_EXECUTION 1
#define DEBUG_WHEEL_CONTROLLER 1
#define DEBUG_STEERING_CONTROLLER 1
#define DEBUG_SPEED_CONTROLLER 0
#define DEBUG_PATH_FOLLOWER 0

#endif
