#!/bin/sh
USBVID=05c6
USBPID=9008

mode=$(cat /sys/kernel/debug/msm_otg/mode)
echo current usb mode: "$mode"
if [ "$mode" != "host" ]; then
  echo configuring usb host mode: PID "$USBPID" VID "$USBVID"...
# echo cpu clock $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq)
  echo none > /sys/kernel/debug/msm_otg/mode
  echo host > /sys/kernel/debug/msm_otg/mode
  sleep 1
  echo 1094400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
  
  echo inserting usbserial module to kernel...
  insmod ./usbserial.ko vendor=0x$USBVID product=0x$USBPID
fi

# Reboot if USB did not switch the first time - only a reboot can fix it
mode=$(cat /sys/kernel/debug/msm_otg/mode)
if [ "$mode" != "host" ]; then
  echo current usb mode: "$mode"
  echo "----------FAILED TO CHANGE USB MODE-----------------"
  #reboot
  exit 1
fi

exit 0
