#!/bin/sh
#
# Start pwr-button utility to monitor S2 and automatically put board into
# suspend on button release.
#

if [ "$1" = "stop" -o "$1" = "restart" ]
then
    echo "Stopping cozmo server: "
    killall python
    killall gst-launch-0.10
    sleep 10
fi

if [ "$1" = "start" -o "$1" = "restart" ]
then
    echo "Starting cozmo server: "
    rsync -a /root/som/ /ramdisk
    cd /ramdisk
    /usr/bin/python server.py &
    cd -
    sleep 1
fi
