# Link Audio Plugins
add_definitions(
  # Effect Plugins
  -DAE_AK_COMPRESSOR_FX
  -DAE_AK_DELAY_FX
  -DAE_AK_METER_FX
  -DAE_AK_EXPANDER_FX
  -DAE_AK_PARAMETRIC_EQ_FX
  -DAE_AK_GAIN_FX
  -DAE_AK_PEAK_LIMITER_FX
  -DAE_AK_PITCH_SHIFTER_FX
  -DAE_AK_TIME_STRETCH_FX
  -DAE_AK_FLANGER_FX
  -DAE_AK_TREMOLO_FX
  -DAE_AK_HARMONIZER_FX
  # Source Plugins	
  -DAE_AK_SILENCE_SOURCE
  -DAE_AK_SINE_GENERATOR_SOURCE
  -DAE_AK_TONE_GENERATOR_SOURCE
)

import(audio "lib/audio")

