#
# Link Audio Plugins
#
set(ANKI_LIB_AUDIO_PLUGINS
  # Effect Plugins
  AE_AK_COMPRESSOR_FX
  AE_AK_DELAY_FX
  AE_AK_METER_FX
  AE_AK_EXPANDER_FX
  AE_AK_PARAMETRIC_EQ_FX
  AE_AK_GAIN_FX
  AE_AK_PEAK_LIMITER_FX
  AE_AK_PITCH_SHIFTER_FX
  AE_AK_TIME_STRETCH_FX
  AE_AK_FLANGER_FX
  AE_AK_TREMOLO_FX
  AE_AK_HARMONIZER_FX
  # Source Plugins	
  AE_AK_SILENCE_SOURCE
  AE_AK_SINE_GENERATOR_SOURCE
  AE_AK_TONE_GENERATOR_SOURCE
)

if(VICOS OR VICOS_STAGING OR VICOS_LA)
list(APPEND ANKI_LIB_AUDIO_PLUGINS
  # Sink Plugins
  AE_AK_ALSA_SINK
)
endif()

import(audio "lib/audio")

