function(prepend_each prefix var)
   set(listVar "")
   set(srcList "${${var}}")
   message(STATUS "srcList = ${srcList}")
   foreach(f ${srcList})
      list(APPEND listVar "${prefix}/${f}")
   endforeach(f)
   set(${var} "${listVar}" PARENT_SCOPE)
   message(STATUS "listVar = ${listVar}")
endfunction(prepend_each)
