# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editGroundTruthWindow.ui'
#
# Created: Fri May 01 10:54:54 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 904)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 241, 221))
        self.groupBox.setObjectName("groupBox")
        self.testJsonFilename1 = QtGui.QLineEdit(self.groupBox)
        self.testJsonFilename1.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.testJsonFilename1.setObjectName("testJsonFilename1")
        self.testJsonFilename2 = QtGui.QLineEdit(self.groupBox)
        self.testJsonFilename2.setGeometry(QtCore.QRect(10, 70, 221, 31))
        self.testJsonFilename2.setObjectName("testJsonFilename2")
        self.test_previous1 = QtGui.QPushButton(self.groupBox)
        self.test_previous1.setGeometry(QtCore.QRect(0, 110, 81, 32))
        self.test_previous1.setObjectName("test_previous1")
        self.test_current = QtGui.QLineEdit(self.groupBox)
        self.test_current.setGeometry(QtCore.QRect(40, 150, 71, 31))
        self.test_current.setObjectName("test_current")
        self.test_max = QtGui.QLineEdit(self.groupBox)
        self.test_max.setGeometry(QtCore.QRect(130, 150, 71, 31))
        self.test_max.setReadOnly(True)
        self.test_max.setObjectName("test_max")
        self.test_previous2 = QtGui.QPushButton(self.groupBox)
        self.test_previous2.setGeometry(QtCore.QRect(80, 110, 81, 32))
        self.test_previous2.setObjectName("test_previous2")
        self.test_previous3 = QtGui.QPushButton(self.groupBox)
        self.test_previous3.setGeometry(QtCore.QRect(160, 110, 81, 32))
        self.test_previous3.setObjectName("test_previous3")
        self.test_next1 = QtGui.QPushButton(self.groupBox)
        self.test_next1.setGeometry(QtCore.QRect(0, 190, 81, 32))
        self.test_next1.setObjectName("test_next1")
        self.test_next2 = QtGui.QPushButton(self.groupBox)
        self.test_next2.setGeometry(QtCore.QRect(80, 190, 81, 32))
        self.test_next2.setObjectName("test_next2")
        self.test_next3 = QtGui.QPushButton(self.groupBox)
        self.test_next3.setGeometry(QtCore.QRect(160, 190, 81, 32))
        self.test_next3.setObjectName("test_next3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(110, 150, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 680, 241, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radio_fiducialMarkerPoints = QtGui.QRadioButton(self.groupBox_4)
        self.radio_fiducialMarkerPoints.setGeometry(QtCore.QRect(10, 30, 151, 18))
        self.radio_fiducialMarkerPoints.setObjectName("radio_fiducialMarkerPoints")
        self.radio_templatePoints = QtGui.QRadioButton(self.groupBox_4)
        self.radio_templatePoints.setGeometry(QtCore.QRect(10, 60, 151, 18))
        self.radio_templatePoints.setObjectName("radio_templatePoints")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 241, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pose_previous1 = QtGui.QPushButton(self.groupBox_2)
        self.pose_previous1.setGeometry(QtCore.QRect(0, 30, 81, 32))
        self.pose_previous1.setObjectName("pose_previous1")
        self.pose_current = QtGui.QLineEdit(self.groupBox_2)
        self.pose_current.setGeometry(QtCore.QRect(40, 70, 71, 31))
        self.pose_current.setObjectName("pose_current")
        self.pose_max = QtGui.QLineEdit(self.groupBox_2)
        self.pose_max.setGeometry(QtCore.QRect(130, 70, 71, 31))
        self.pose_max.setReadOnly(True)
        self.pose_max.setObjectName("pose_max")
        self.pose_previous2 = QtGui.QPushButton(self.groupBox_2)
        self.pose_previous2.setGeometry(QtCore.QRect(80, 30, 81, 32))
        self.pose_previous2.setObjectName("pose_previous2")
        self.pose_previous3 = QtGui.QPushButton(self.groupBox_2)
        self.pose_previous3.setGeometry(QtCore.QRect(160, 30, 81, 32))
        self.pose_previous3.setObjectName("pose_previous3")
        self.pose_next1 = QtGui.QPushButton(self.groupBox_2)
        self.pose_next1.setGeometry(QtCore.QRect(0, 110, 81, 32))
        self.pose_next1.setObjectName("pose_next1")
        self.pose_next2 = QtGui.QPushButton(self.groupBox_2)
        self.pose_next2.setGeometry(QtCore.QRect(80, 110, 81, 32))
        self.pose_next2.setObjectName("pose_next2")
        self.pose_next3 = QtGui.QPushButton(self.groupBox_2)
        self.pose_next3.setGeometry(QtCore.QRect(160, 110, 81, 32))
        self.pose_next3.setObjectName("pose_next3")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pose_filename = QtGui.QLabel(self.groupBox_2)
        self.pose_filename.setGeometry(QtCore.QRect(10, 140, 451, 21))
        self.pose_filename.setTextFormat(QtCore.Qt.PlainText)
        self.pose_filename.setScaledContents(True)
        self.pose_filename.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.pose_filename.setObjectName("pose_filename")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 241, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.marker_previous1 = QtGui.QPushButton(self.groupBox_3)
        self.marker_previous1.setGeometry(QtCore.QRect(0, 30, 81, 32))
        self.marker_previous1.setObjectName("marker_previous1")
        self.marker_current = QtGui.QLineEdit(self.groupBox_3)
        self.marker_current.setGeometry(QtCore.QRect(40, 70, 71, 31))
        self.marker_current.setObjectName("marker_current")
        self.marker_max = QtGui.QLineEdit(self.groupBox_3)
        self.marker_max.setGeometry(QtCore.QRect(130, 70, 71, 31))
        self.marker_max.setReadOnly(True)
        self.marker_max.setObjectName("marker_max")
        self.marker_previous2 = QtGui.QPushButton(self.groupBox_3)
        self.marker_previous2.setGeometry(QtCore.QRect(80, 30, 81, 32))
        self.marker_previous2.setObjectName("marker_previous2")
        self.marker_previous3 = QtGui.QPushButton(self.groupBox_3)
        self.marker_previous3.setGeometry(QtCore.QRect(160, 30, 81, 32))
        self.marker_previous3.setObjectName("marker_previous3")
        self.marker_next1 = QtGui.QPushButton(self.groupBox_3)
        self.marker_next1.setGeometry(QtCore.QRect(0, 110, 81, 32))
        self.marker_next1.setObjectName("marker_next1")
        self.marker_next2 = QtGui.QPushButton(self.groupBox_3)
        self.marker_next2.setGeometry(QtCore.QRect(80, 110, 81, 32))
        self.marker_next2.setObjectName("marker_next2")
        self.marker_next3 = QtGui.QPushButton(self.groupBox_3)
        self.marker_next3.setGeometry(QtCore.QRect(160, 110, 81, 32))
        self.marker_next3.setObjectName("marker_next3")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.markerType = QtGui.QLineEdit(self.groupBox_3)
        self.markerType.setGeometry(QtCore.QRect(10, 150, 221, 21))
        self.markerType.setObjectName("markerType")
        self.trackMarkerAcrossPoses = QtGui.QPushButton(self.groupBox_3)
        self.trackMarkerAcrossPoses.setGeometry(QtCore.QRect(0, 180, 241, 32))
        self.trackMarkerAcrossPoses.setObjectName("trackMarkerAcrossPoses")
        self.clearAllMarkers = QtGui.QPushButton(self.groupBox_3)
        self.clearAllMarkers.setGeometry(QtCore.QRect(0, 240, 241, 32))
        self.clearAllMarkers.setObjectName("clearAllMarkers")
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(10, 780, 241, 81))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 256, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Test Json Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.test_previous1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.test_previous2.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.test_previous3.setText(QtGui.QApplication.translate("MainWindow", "-100", None, QtGui.QApplication.UnicodeUTF8))
        self.test_next1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.test_next2.setText(QtGui.QApplication.translate("MainWindow", "+10", None, QtGui.QApplication.UnicodeUTF8))
        self.test_next3.setText(QtGui.QApplication.translate("MainWindow", "+100", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", " /", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Labeling Type", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fiducialMarkerPoints.setText(QtGui.QApplication.translate("MainWindow", "Fiducial Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_templatePoints.setText(QtGui.QApplication.translate("MainWindow", "Template Points", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Pose (Image)", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_previous1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_previous2.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_previous3.setText(QtGui.QApplication.translate("MainWindow", "-100", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_next1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_next2.setText(QtGui.QApplication.translate("MainWindow", "+10", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_next3.setText(QtGui.QApplication.translate("MainWindow", "+100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", " /", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_filename.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_previous1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_previous2.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_previous3.setText(QtGui.QApplication.translate("MainWindow", "-100", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_next1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_next2.setText(QtGui.QApplication.translate("MainWindow", "+10", None, QtGui.QApplication.UnicodeUTF8))
        self.marker_next3.setText(QtGui.QApplication.translate("MainWindow", "+100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", " /", None, QtGui.QApplication.UnicodeUTF8))
        self.trackMarkerAcrossPoses.setText(QtGui.QApplication.translate("MainWindow", "Track marker across poses", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAllMarkers.setText(QtGui.QApplication.translate("MainWindow", "Clear all markers", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">Instructions:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">Left click to create a new point</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">Right click to remove a point</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">Shift+ left click in the center of a quad, to select it</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">  </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:7pt;\">All changes are automatically saved</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

