// Autogenerated C++ message buffer code.
// Source: clad/types/faceEnrollmentResult.clad
// Full command line: victor-clad/tools/message-buffers/emitters/CPP_emitter.py --output-union-helper-constructors -C sdk -I victor-clad/clad/sdk -o generated/clad clad/types/faceEnrollmentResult.clad

#ifndef __CLAD_TYPES_FACE_ENROLLMENT_RESULT_H__
#define __CLAD_TYPES_FACE_ENROLLMENT_RESULT_H__

#include <CLAD/SafeMessageBuffer.h>
#include <array>
#include <cassert>
#include <cstdint>
#include <string>
#include <vector>

namespace Anki {

namespace Vector {

// ENUM FaceEnrollmentResult
enum class FaceEnrollmentResult : uint8_t {
  Success          = 0,
  SawWrongFace     = 1,
  SawMultipleFaces = 2,
  TimedOut         = 3,
  SaveFailed       = 4,
  Incomplete       = 5,
  Cancelled        = 6,
  NameInUse        = 7,
  UnknownFailure   = 8,
};

const char* EnumToString(const FaceEnrollmentResult m);
inline const char* FaceEnrollmentResultToString(const FaceEnrollmentResult m) { return EnumToString(m); }


extern const char* FaceEnrollmentResultVersionHashStr;
extern const uint8_t FaceEnrollmentResultVersionHash[16];

constexpr uint8_t FaceEnrollmentResultNumEntries = 9;

} // namespace Vector

} // namespace Anki

#endif // __CLAD_TYPES_FACE_ENROLLMENT_RESULT_H__
